import { InteractionRuntimeError } from './DataResourceOwner.js';
import type { InteractionActionPort, InteractionGeometryPort, RoutedInteractionEvent, RuntimeInteractionAction, RuntimeInteractionDocument, RuntimeInteractionListener, RuntimeInteractionTarget, RuntimeValue } from './runtime-types.js';

interface PointerInput { readonly kind: 'move' | 'down' | 'up'; readonly pointerId: number; readonly point: readonly [number, number]; readonly button?: number }
interface QueuedEvent { readonly kind: string; readonly target: string; readonly depth: number; readonly pointerId?: number; readonly point?: readonly [number, number]; readonly button?: number; readonly key?: string; readonly keyPhase?: string; readonly modifiers?: readonly string[]; readonly text?: string; readonly binding?: string; readonly value?: RuntimeValue; readonly gamepad?: Readonly<{ index: number; control: string; phase: string; value: number }>; readonly semanticAction?: string; readonly name?: string; readonly payload?: RuntimeValue }
interface PointerState { point: readonly [number, number]; hover: string | undefined; down: string | undefined; downPoint: readonly [number, number] | undefined; dragging: boolean }
interface Snapshot { pointers: Map<number, PointerState>; captures: Map<number, string>; focus: string | undefined; queue: QueuedEvent[] }
export interface InteractionRuntimeOptions { readonly geometryPort?: InteractionGeometryPort; readonly actionPort?: InteractionActionPort; readonly maxEventQueue?: number; readonly maxEventRecursion?: number; readonly maxPointers?: number; readonly maxStringBytes?: number }

export class InteractionRuntime {
  private readonly targets: Map<string, RuntimeInteractionTarget>; private readonly listeners: Map<string, RuntimeInteractionListener[]>; private readonly queue: QueuedEvent[] = [];
  private pointers = new Map<number, PointerState>(); private captures = new Map<number, string>(); private focused: string | undefined; private sequence = 0; private transactionSequence = 0; private draining = false; private currentDepth = 0; private disposed = false;
  private readonly maxEventQueue: number; private readonly maxEventRecursion: number; private readonly maxPointers: number; private readonly maxStringBytes: number;
  constructor(readonly document: RuntimeInteractionDocument, private readonly options: InteractionRuntimeOptions = {}) { this.targets = new Map(document.targets.map(target => [target.id, target])); this.listeners = new Map(); for (const listener of document.listeners) { const values = this.listeners.get(listener.target) ?? []; values.push(listener); this.listeners.set(listener.target, values); } this.maxEventQueue = options.maxEventQueue ?? document.limits?.maxEventQueue ?? 1_000_000; this.maxEventRecursion = options.maxEventRecursion ?? document.limits?.maxEventRecursion ?? 64; this.maxPointers = options.maxPointers ?? document.limits?.maxPointers ?? 1_024; this.maxStringBytes = options.maxStringBytes ?? 4 * 1024 * 1024; }
  dispatchPointer(input: PointerInput): void { this.assertLive(); if (!Number.isSafeInteger(input.pointerId) || input.pointerId < 0 || input.point.some(value => !Number.isFinite(value))) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_LIMIT', '$.pointer', 'invalid pointer input'); let state = this.pointers.get(input.pointerId); if (!state) { if (this.pointers.size >= this.maxPointers) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_LIMIT', '$.pointers', 'pointer budget exceeded'); state = { point: input.point, hover: undefined, down: undefined, downPoint: undefined, dragging: false }; this.pointers.set(input.pointerId, state); } const hit = this.captures.get(input.pointerId) ?? this.hitTest(input.point), previousHover = state.hover; state.point = input.point;
    if (input.kind === 'move' && previousHover !== hit) { if (previousHover) this.enqueue({ kind: 'pointer-exit', target: previousHover, depth: 0, pointerId: input.pointerId, point: input.point }); if (hit) this.enqueue({ kind: 'pointer-enter', target: hit, depth: 0, pointerId: input.pointerId, point: input.point }); state.hover = hit; }
    if (input.kind === 'down') { state.down = hit; state.downPoint = input.point; state.dragging = false; if (hit) { this.enqueue({ kind: 'pointer-down', target: hit, depth: 0, pointerId: input.pointerId, point: input.point, button: input.button ?? 0 }); this.focusFromPointer(hit); } }
    else if (input.kind === 'move') { if (hit) this.enqueue({ kind: 'pointer-move', target: hit, depth: 0, pointerId: input.pointerId, point: input.point }); if (state.down && state.downPoint) { const distance = Math.hypot(input.point[0] - state.downPoint[0], input.point[1] - state.downPoint[1]); if (!state.dragging && distance >= this.document.dragThreshold) { state.dragging = true; this.enqueue({ kind: 'drag-start', target: state.down, depth: 0, pointerId: input.pointerId, point: input.point }); } if (state.dragging) this.enqueue({ kind: 'drag', target: state.down, depth: 0, pointerId: input.pointerId, point: input.point }); } }
    else { if (hit) this.enqueue({ kind: 'pointer-up', target: hit, depth: 0, pointerId: input.pointerId, point: input.point, button: input.button ?? 0 }); if (state.down) { if (state.dragging) this.enqueue({ kind: 'drag-end', target: state.down, depth: 0, pointerId: input.pointerId, point: input.point }); else if (hit === state.down) this.enqueue({ kind: 'click', target: state.down, depth: 0, pointerId: input.pointerId, point: input.point, button: input.button ?? 0 }); } state.down = undefined; state.downPoint = undefined; state.dragging = false; this.captures.delete(input.pointerId); }
    this.drain();
  }
  dispatchKeyboard(input: Readonly<{ key: string; phase: 'down' | 'up' | 'repeat'; modifiers?: readonly string[] }>): void { this.assertLive(); if (!this.focused) return; this.enqueue({ kind: 'keyboard', target: this.focused, depth: 0, key: input.key, keyPhase: input.phase, modifiers: input.modifiers ?? [] }); this.drain(); }
  dispatchText(text: string): void { this.assertLive(); this.stringInput(text, '$.text'); if (!this.focused) return; this.enqueue({ kind: 'text-input', target: this.focused, depth: 0, text }); this.drain(); }
  dispatchDataChange(binding: string, value: RuntimeValue, target = this.focused): void { this.assertLive(); this.stringInput(binding, '$.binding'); if (!target) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', binding, 'data change requires a target'); this.enqueue({ kind: 'data-change', target, depth: 0, binding, value }); this.drain(); }
  dispatchGamepad(input: Readonly<{ index: number; control: string; phase: 'down' | 'up' | 'change'; value: number }>): void { this.assertLive(); if (!this.focused) return; this.enqueue({ kind: 'gamepad', target: this.focused, depth: 0, gamepad: input }); this.drain(); }
  dispatchSemanticAction(target: string, action: 'tap' | 'increase' | 'decrease' | 'focus'): void { this.assertLive(); this.target(target); this.enqueue({ kind: 'semantic-action', target, depth: 0, semanticAction: action }); this.drain(); }
  enqueueReportedEvent(name: string, payload: RuntimeValue = null, target = this.focused): void { this.assertLive(); this.stringInput(name, '$.event.name'); if (!target) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', name, 'reported event requires a target'); this.enqueue({ kind: 'reported-event', target, depth: this.draining ? this.currentDepth + 1 : 0, name, payload }); if (!this.draining) this.drain(); }
  enqueueComponentEvent(target: string, name: string, payload: RuntimeValue = null): void { this.assertLive(); this.stringInput(name, '$.componentEvent.name'); this.enqueue({ kind: 'component-event', target, depth: this.draining ? this.currentDepth + 1 : 0, name, payload }); if (!this.draining) this.drain(); }
  focus(target: string | undefined): void { this.assertLive(); if (target !== undefined) { const item = this.target(target); if (!item.focusable || item.enabled === false) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', target, 'target is not focusable'); } if (this.focused === target) return; const previous = this.focused; this.focused = target; if (previous) this.enqueue({ kind: 'blur', target: previous, depth: this.draining ? this.currentDepth + 1 : 0 }); if (target) this.enqueue({ kind: 'focus', target, depth: this.draining ? this.currentDepth + 1 : 0 }); if (!this.draining) this.drain(); }
  focusNext(reverse = false): string | undefined { const ordered = [...this.targets.values()].filter(target => target.focusable && target.enabled !== false).sort((a, b) => (a.tabIndex ?? 0) - (b.tabIndex ?? 0) || a.order - b.order || a.id.localeCompare(b.id)); if (ordered.length === 0) { this.focus(undefined); return undefined; } const current = ordered.findIndex(target => target.id === this.focused), delta = reverse ? -1 : 1, index = (current + delta + ordered.length) % ordered.length; this.focus(ordered[index]!.id); return this.focused; }
  hitTest(point: readonly [number, number]): string | undefined { this.assertLive(); return [...this.targets.values()].filter(target => target.enabled !== false && this.options.geometryPort?.visible?.(target.id) !== false).sort((a, b) => b.order - a.order || b.id.localeCompare(a.id)).find(target => this.containsTarget(target, point, true))?.id; }
  dispose(): void { if (this.disposed) return; this.disposed = true; this.queue.length = 0; this.pointers.clear(); this.captures.clear(); this.focused = undefined; this.options.actionPort?.dispose?.(); }
  get trace(): Readonly<{ sequence: number; focused: string | null; captures: readonly Readonly<{ pointer: number; target: string }>[]; pointers: number; queued: number; disposed: boolean }> { return Object.freeze({ sequence: this.sequence, focused: this.focused ?? null, captures: Object.freeze([...this.captures].map(([pointer, target]) => Object.freeze({ pointer, target }))), pointers: this.pointers.size, queued: this.queue.length, disposed: this.disposed }); }

  private enqueue(event: QueuedEvent): void { if (event.depth > this.maxEventRecursion) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_LIMIT', '$.events', 'event recursion budget exceeded'); if (this.queue.length >= this.maxEventQueue) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_LIMIT', '$.events', 'event queue budget exceeded'); this.target(event.target); this.queue.push(event); }
  private drain(): void { if (this.draining) return; this.draining = true; try { while (this.queue.length) { const event = this.queue.shift()!; this.currentDepth = event.depth; this.route(event); } } finally { this.currentDepth = 0; this.draining = false; } }
  private route(event: QueuedEvent): void { const path = this.path(event.target), transactionId = ++this.transactionSequence, snapshot = this.snapshot(); const actionPort = this.options.actionPort; actionPort?.begin(transactionId); try { for (const current of path.slice(0, -1)) this.invokeListeners(current, 'capture', event, transactionId); this.invokeListeners(event.target, 'target', event, transactionId); for (const current of path.slice(0, -1).reverse()) this.invokeListeners(current, 'bubble', event, transactionId); actionPort?.commit(transactionId); } catch (error) { this.restore(snapshot); actionPort?.rollback(transactionId); throw error; } }
  private invokeListeners(currentTarget: string, phase: RoutedInteractionEvent['phase'], event: QueuedEvent, transactionId: number): void { void transactionId; const listeners = this.listeners.get(currentTarget) ?? []; for (const listener of listeners) { if (listener.event !== event.kind || !listener.phases.includes(phase) || !this.matches(listener, event)) continue; const routed = Object.freeze({ sequence: ++this.sequence, kind: event.kind, phase, target: event.target, currentTarget, ...(event.pointerId === undefined ? {} : { pointerId: event.pointerId }), ...(event.point === undefined ? {} : { point: event.point, localPoint: this.toLocal(currentTarget, event.point) }), ...(event.button === undefined ? {} : { button: event.button }), ...(event.key === undefined ? {} : { key: event.key }), ...(event.keyPhase === undefined ? {} : { keyPhase: event.keyPhase }), ...(event.modifiers === undefined ? {} : { modifiers: event.modifiers }), ...(event.text === undefined ? {} : { text: event.text }), ...(event.binding === undefined ? {} : { binding: event.binding }), ...(event.value === undefined ? {} : { value: event.value }), ...(event.gamepad === undefined ? {} : { gamepad: event.gamepad }), ...(event.semanticAction === undefined ? {} : { semanticAction: event.semanticAction }), ...(event.name === undefined ? {} : { name: event.name }), ...(event.payload === undefined ? {} : { payload: event.payload }) }) as RoutedInteractionEvent; for (const action of listener.actions) this.invokeAction(action, routed); } }
  private invokeAction(action: RuntimeInteractionAction, event: RoutedInteractionEvent): void { if (action.kind === 'pointer-capture') { if (event.pointerId === undefined) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', event.currentTarget, 'pointer capture requires a pointer event'); this.captures.set(event.pointerId, event.currentTarget); } else if (action.kind === 'pointer-release') { if (event.pointerId !== undefined) this.captures.delete(event.pointerId); } else if (action.kind === 'focus') this.focus((action.target as string | undefined) ?? event.currentTarget); const port = this.options.actionPort; if (!port && !['pointer-capture', 'pointer-release', 'focus'].includes(action.kind)) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', event.currentTarget, `action port is required for ${action.kind}`); port?.invoke(action, event); }
  private matches(listener: RuntimeInteractionListener, event: QueuedEvent): boolean { if (listener.pointerButton !== undefined && listener.pointerButton !== event.button) return false; if (listener.key !== undefined && listener.key !== event.key) return false; if (listener.keyPhase !== undefined && listener.keyPhase !== event.keyPhase) return false; if (listener.modifiers && !listener.modifiers.every(modifier => event.modifiers?.includes(modifier))) return false; if (listener.gamepad && (!event.gamepad || (listener.gamepad.index !== undefined && listener.gamepad.index !== event.gamepad.index) || listener.gamepad.control !== event.gamepad.control || listener.gamepad.phase !== event.gamepad.phase)) return false; if (listener.semanticAction !== undefined && listener.semanticAction !== event.semanticAction) return false; return true; }
  private containsTarget(target: RuntimeInteractionTarget, point: readonly [number, number], clips: boolean): boolean { const local = this.toLocal(target.id, point); if (clips && target.clips?.some(id => !this.containsTarget(this.target(id), point, false))) return false; const area = target.hitArea, kind = area.kind; if (kind === 'rect') { const [x, y, width, height] = area.rect as readonly number[]; return local[0] >= x! && local[1] >= y! && local[0] <= x! + width! && local[1] <= y! + height!; } if (kind === 'ellipse') { const center = area.center as readonly number[], radius = area.radius as readonly number[]; if (radius[0] === 0 || radius[1] === 0) return false; return ((local[0] - center[0]!) / radius[0]!) ** 2 + ((local[1] - center[1]!) / radius[1]!) ** 2 <= 1; } if (kind === 'polygon') return pointInPolygon(local, area.points as readonly (readonly [number, number])[]); if (kind === 'geometry') { const port = this.options.geometryPort?.containsGeometry; if (!port) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', target.id, 'geometry hit area requires a geometry port'); return port(area.port as string, target.id, local); } return false; }
  private toLocal(id: string, point: readonly [number, number]): readonly [number, number] { const chain = this.path(id); let matrix: Matrix = [1, 0, 0, 1, 0, 0]; for (const targetId of chain) { const target = this.target(targetId), authored = target.transform as Matrix | undefined, dynamic = this.options.geometryPort?.matrix?.(targetId) as Matrix | undefined; if (authored) matrix = multiply(matrix, authored); if (dynamic) matrix = multiply(matrix, dynamic); } return transform(inverse(matrix), point); }
  private path(id: string): string[] { const result: string[] = []; let current: RuntimeInteractionTarget | undefined = this.target(id); while (current) { result.unshift(current.id); current = current.parent ? this.target(current.parent) : undefined; } return result; }
  private focusFromPointer(id: string): void { let target: RuntimeInteractionTarget | undefined = this.target(id); while (target && !target.focusable) target = target.parent ? this.target(target.parent) : undefined; if (target?.focusable) this.focus(target.id); }
  private target(id: string): RuntimeInteractionTarget { const target = this.targets.get(id); if (!target) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', id, 'unknown interaction target'); return target; }
  private snapshot(): Snapshot { return { pointers: new Map([...this.pointers].map(([id, state]) => [id, { ...state }])), captures: new Map(this.captures), focus: this.focused, queue: [...this.queue] }; }
  private restore(snapshot: Snapshot): void { this.pointers = snapshot.pointers; this.captures = snapshot.captures; this.focused = snapshot.focus; this.queue.splice(0, this.queue.length, ...snapshot.queue); }
  private stringInput(value: string, path: string): void { if (typeof value !== 'string' || new TextEncoder().encode(value).length > this.maxStringBytes) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_LIMIT', path, 'string input exceeds budget'); }
  private assertLive(): void { if (this.disposed) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', '$', 'interaction runtime is disposed'); }
}

type Matrix = readonly [number, number, number, number, number, number];
function multiply(a: Matrix, b: Matrix): Matrix { return [a[0] * b[0] + a[2] * b[1], a[1] * b[0] + a[3] * b[1], a[0] * b[2] + a[2] * b[3], a[1] * b[2] + a[3] * b[3], a[0] * b[4] + a[2] * b[5] + a[4], a[1] * b[4] + a[3] * b[5] + a[5]]; }
function inverse(value: Matrix): Matrix { const determinant = value[0] * value[3] - value[1] * value[2]; if (Math.abs(determinant) < 1e-12) throw new InteractionRuntimeError('E_INTERACTION_RUNTIME_PORT', '$.transform', 'interaction transform is singular'); return [value[3] / determinant, -value[1] / determinant, -value[2] / determinant, value[0] / determinant, (value[2] * value[5] - value[3] * value[4]) / determinant, (value[1] * value[4] - value[0] * value[5]) / determinant]; }
function transform(matrix: Matrix, point: readonly [number, number]): readonly [number, number] { return [matrix[0] * point[0] + matrix[2] * point[1] + matrix[4], matrix[1] * point[0] + matrix[3] * point[1] + matrix[5]]; }
function pointInPolygon(point: readonly [number, number], points: readonly (readonly [number, number])[]): boolean { let inside = false; for (let index = 0, previous = points.length - 1; index < points.length; previous = index++) { const a = points[index]!, b = points[previous]!, crosses = a[1] > point[1] !== b[1] > point[1] && point[0] < (b[0] - a[0]) * (point[1] - a[1]) / (b[1] - a[1]) + a[0]; if (crosses) inside = !inside; } return inside; }
