export interface RuntimeObject { readonly [key: string]: RuntimeValue }
export type RuntimeValue = number | string | boolean | null | readonly RuntimeValue[] | RuntimeObject;
export type RuntimePath = readonly (string | number)[];
export interface RuntimeProperty { readonly id: string; readonly kind: 'number' | 'integer' | 'string' | 'boolean' | 'color' | 'trigger' | 'enum' | 'model' | 'list' | 'image' | 'artboard' | 'font' | 'blob'; readonly enum?: string; readonly model?: string; readonly item?: Readonly<{ kind: string; enum?: string; model?: string }>; readonly defaultValue?: RuntimeValue; readonly nullable?: boolean }
export interface RuntimeModel { readonly id: string; readonly properties: readonly RuntimeProperty[]; readonly defaultInstance?: string }
export interface RuntimeInstance { readonly id: string; readonly model: string; readonly scope: 'default' | 'global' | 'local'; readonly values: Readonly<Record<string, RuntimeValue>> }
export interface RuntimeConverter { readonly id: string; readonly version: 1; readonly operations: readonly Readonly<Record<string, unknown>>[] }
export interface RuntimeBinding { readonly id: string; readonly target: string; readonly targetPath: readonly string[]; readonly source: Readonly<{ mode: 'explicit' | 'default' | 'global' | 'auto'; instance?: string; model?: string; path: RuntimePath }>; readonly converter?: string; readonly direction: 'read' | 'write' | 'two-way' }
export interface RuntimePropertyGroup { readonly id: string; readonly version: 1; readonly operations: readonly Readonly<Record<string, unknown>>[] }
export interface RuntimeDataComponent { readonly id: string; readonly stateful: true; readonly model: string; readonly exposedProperties?: readonly string[]; readonly exposedInputs?: readonly string[]; readonly exposedEvents?: readonly string[] }
export interface RuntimeDataDocument { readonly enums: readonly Readonly<{ id: string; values: readonly Readonly<{ key: string; value: number }>[] }>[]; readonly models: readonly RuntimeModel[]; readonly instances: readonly RuntimeInstance[]; readonly converters: readonly RuntimeConverter[]; readonly propertyGroups: readonly RuntimePropertyGroup[]; readonly bindings: readonly RuntimeBinding[]; readonly components: readonly RuntimeDataComponent[] }

export interface DataChange { readonly sequence: number; readonly transactionId: number; readonly instance: string; readonly path: RuntimePath; readonly kind: 'set' | 'trigger' | 'list-insert' | 'list-remove' | 'list-move' | 'rebind'; readonly previous: RuntimeValue | undefined; readonly value: RuntimeValue | undefined }
export interface DataObservationBatch { readonly advance: number; readonly changes: readonly DataChange[] }
export interface DataSubscription { unsubscribe(): void }
export interface CustomConverterPort { begin(transactionId: number): void; invoke(request: Readonly<{ protocol: string; port: string; value: RuntimeValue; arguments: Readonly<Record<string, RuntimeValue>> }>): RuntimeValue; commit(transactionId: number): void; rollback(transactionId: number): void; dispose?(): void }
export interface DataResourceHandle { readonly value: unknown; release(): void }
export interface DataResourcePort { acquire(kind: 'image' | 'artboard' | 'font' | 'blob', id: string, signal: AbortSignal): Promise<DataResourceHandle> }

export type RuntimeHitArea = Readonly<Record<string, unknown>>;
export interface RuntimeInteractionTarget { readonly id: string; readonly parent?: string; readonly component?: string; readonly order: number; readonly transform?: readonly [number, number, number, number, number, number]; readonly hitArea: RuntimeHitArea; readonly clips?: readonly string[]; readonly enabled?: boolean; readonly focusable?: boolean; readonly tabIndex?: number }
export interface RuntimeInteractionAction extends Readonly<Record<string, unknown>> { readonly kind: string }
export interface RuntimeInteractionListener { readonly id: string; readonly target: string; readonly event: string; readonly phases: readonly ('capture' | 'target' | 'bubble')[]; readonly pointerButton?: number; readonly key?: string; readonly keyPhase?: string; readonly modifiers?: readonly string[]; readonly gamepad?: Readonly<{ index?: number; control: string; phase: string }>; readonly semanticAction?: string; readonly actions: readonly RuntimeInteractionAction[] }
export interface RuntimeInteractionDocument { readonly dragThreshold: number; readonly targets: readonly RuntimeInteractionTarget[]; readonly listeners: readonly RuntimeInteractionListener[]; readonly limits?: Readonly<{ maxEventQueue?: number; maxEventRecursion?: number; maxPointers?: number }> }
export interface InteractionGeometryPort { matrix?(target: string): readonly [number, number, number, number, number, number] | undefined; visible?(target: string): boolean; containsGeometry?(port: string, target: string, localPoint: readonly [number, number]): boolean }
export interface RoutedInteractionEvent { readonly sequence: number; readonly kind: string; readonly phase: 'capture' | 'target' | 'bubble'; readonly target: string; readonly currentTarget: string; readonly pointerId?: number; readonly point?: readonly [number, number]; readonly localPoint?: readonly [number, number]; readonly button?: number; readonly key?: string; readonly keyPhase?: string; readonly modifiers?: readonly string[]; readonly text?: string; readonly binding?: string; readonly value?: RuntimeValue; readonly gamepad?: Readonly<{ index: number; control: string; phase: string; value: number }>; readonly semanticAction?: string; readonly name?: string; readonly payload?: RuntimeValue }
export interface InteractionActionPort { begin(transactionId: number): void; invoke(action: RuntimeInteractionAction, event: RoutedInteractionEvent): void; commit(transactionId: number): void; rollback(transactionId: number): void; dispose?(): void }

export interface RuntimeSemanticValue { readonly kind: 'literal' | 'binding'; readonly value?: RuntimeValue; readonly binding?: string }
export interface RuntimeSemanticNode { readonly id: string; readonly target: string; readonly parent?: string; readonly role: string; readonly label?: RuntimeSemanticValue; readonly value?: RuntimeSemanticValue; readonly hint?: RuntimeSemanticValue; readonly headingLevel?: number; readonly traits?: readonly string[]; readonly state?: Readonly<Record<string, RuntimeSemanticValue>>; readonly capabilities?: Readonly<Record<string, boolean>>; readonly actions?: readonly string[]; readonly live?: string; readonly readingOrder: number; readonly navigationOrder: number }
export interface RuntimeSemanticsDocument { readonly nodes: readonly RuntimeSemanticNode[]; readonly reducedMotion: Readonly<Record<string, unknown>> }
export interface SemanticSnapshotNode { readonly id: string; readonly target: string; readonly parent?: string; readonly role: string; readonly label?: string; readonly value?: string | number; readonly hint?: string; readonly headingLevel?: number; readonly traits: readonly string[]; readonly state: Readonly<Record<string, boolean>>; readonly capabilities: Readonly<Record<string, boolean>>; readonly actions: readonly string[]; readonly live: string; readonly readingOrder: number; readonly navigationOrder: number }
export interface SemanticSnapshot { readonly revision: number; readonly nodes: readonly SemanticSnapshotNode[]; readonly readingOrder: readonly string[]; readonly navigationOrder: readonly string[]; readonly announcements: readonly Readonly<{ node: string; mode: string; text: string }>[] }
export interface SemanticBindingPort { read(binding: string): RuntimeValue; subscribe?(listener: () => void): DataSubscription }
export interface SemanticHostBridge { update(snapshot: SemanticSnapshot): void; subscribeActions?(listener: (node: string, action: string) => void): DataSubscription; dispose?(): void }
export interface SemanticActionPort { invoke(target: string, action: string): void }
