import { InteractionRuntimeError } from './DataResourceOwner.js';
import type { DataSubscription, RuntimeSemanticNode, RuntimeSemanticValue, RuntimeSemanticsDocument, RuntimeValue, SemanticActionPort, SemanticBindingPort, SemanticHostBridge, SemanticSnapshot, SemanticSnapshotNode } from './runtime-types.js';

export class SemanticsRuntime {
  private bindingSubscription: DataSubscription | undefined; private actionSubscription: DataSubscription | undefined; private revision = 0; private disposed = false; private previous = new Map<string, SemanticSnapshotNode>(); private snapshotValue: SemanticSnapshot = Object.freeze({ revision: 0, nodes: Object.freeze([]), readingOrder: Object.freeze([]), navigationOrder: Object.freeze([]), announcements: Object.freeze([]) });
  constructor(readonly document: RuntimeSemanticsDocument, private bindingPort: SemanticBindingPort, private bridge: SemanticHostBridge, private readonly actionPort: SemanticActionPort) { try { this.attach(); this.update(); } catch (error) { this.detach(); this.disposed = true; this.bridge.dispose?.(); throw error; } }
  update(): SemanticSnapshot { this.assertLive(); const resolved = new Map<string, SemanticSnapshotNode>(), hidden = new Set<string>(); for (const node of this.document.nodes) { const state = Object.freeze(Object.fromEntries(Object.entries(node.state ?? {}).map(([key, value]) => [key, boolean(this.resolve(value), `semantics.${node.id}.state.${key}`)]))), parentHidden = node.parent ? hidden.has(node.parent) : false; if (parentHidden || state.hidden) { hidden.add(node.id); continue; } const snapshot = freezeNode({ id: node.id, target: node.target, ...(node.parent === undefined ? {} : { parent: node.parent }), role: node.role, ...(node.label === undefined ? {} : { label: string(this.resolve(node.label), `semantics.${node.id}.label`) }), ...(node.value === undefined ? {} : { value: stringOrNumber(this.resolve(node.value), `semantics.${node.id}.value`) }), ...(node.hint === undefined ? {} : { hint: string(this.resolve(node.hint), `semantics.${node.id}.hint`) }), ...(node.headingLevel === undefined ? {} : { headingLevel: node.headingLevel }), traits: Object.freeze([...(node.traits ?? [])]), state, capabilities: Object.freeze({ ...(node.capabilities ?? {}) }), actions: Object.freeze([...(node.actions ?? [])]), live: node.live ?? 'off', readingOrder: node.readingOrder, navigationOrder: node.navigationOrder }); resolved.set(node.id, snapshot); }
    const nodes = Object.freeze([...resolved.values()].sort((a, b) => a.readingOrder - b.readingOrder || a.id.localeCompare(b.id))), readingOrder = Object.freeze(nodes.map(node => node.id)), navigationOrder = Object.freeze([...resolved.values()].filter(node => !node.state.disabled && node.actions.length > 0).sort((a, b) => a.navigationOrder - b.navigationOrder || a.id.localeCompare(b.id)).map(node => node.id)), announcements: Array<{ node: string; mode: string; text: string }> = [];
    if (this.revision > 0) for (const node of nodes) { if (node.live === 'off') continue; const before = this.previous.get(node.id), text = `${node.label ?? ''}${node.value === undefined ? '' : ` ${node.value}`}`.trim(), previousText = before ? `${before.label ?? ''}${before.value === undefined ? '' : ` ${before.value}`}`.trim() : ''; if (text !== previousText) announcements.push(Object.freeze({ node: node.id, mode: node.live, text })); }
    const next = Object.freeze({ revision: this.revision + 1, nodes, readingOrder, navigationOrder, announcements: Object.freeze(announcements) }); this.bridge.update(next); this.previous = resolved; this.snapshotValue = next; this.revision = next.revision; return next;
  }
  rebind(bindingPort: SemanticBindingPort, bridge = this.bridge): void { this.assertLive(); const previousBinding = this.bindingPort, previousBridge = this.bridge, previousNodes = this.previous, previousSnapshot = this.snapshotValue, previousRevision = this.revision; this.detach(); this.bindingPort = bindingPort; this.bridge = bridge; this.previous = new Map(); try { this.attach(); this.update(); if (bridge !== previousBridge) previousBridge.dispose?.(); } catch (error) { this.detach(); if (bridge !== previousBridge) bridge.dispose?.(); this.bindingPort = previousBinding; this.bridge = previousBridge; this.previous = previousNodes; this.snapshotValue = previousSnapshot; this.revision = previousRevision; this.attach(); throw error; } }
  perform(nodeId: string, action: string): void { this.assertLive(); const node = this.snapshotValue.nodes.find(candidate => candidate.id === nodeId); if (!node || !node.actions.includes(action) || node.state.disabled) throw new InteractionRuntimeError('E_SEMANTICS_RUNTIME_PORT', nodeId, `semantic action ${action} is not available`); this.actionPort.invoke(node.target, action); }
  resolveReducedMotion(prefersReducedMotion: boolean, essential: boolean): Readonly<{ animate: boolean; durationScale: number; disableParallax: boolean }> { const policy = this.document.reducedMotion; if (!prefersReducedMotion || policy.mode === 'ignore') return Object.freeze({ animate: true, durationScale: 1, disableParallax: false }); const decorative = policy.decorative as string, essentialMode = policy.essential as string; return Object.freeze({ animate: essential ? essentialMode === 'retain' || (policy.durationScale as number) > 0 : decorative === 'continue', durationScale: essential && essentialMode === 'retain' ? 1 : policy.durationScale as number, disableParallax: policy.disableParallax as boolean }); }
  dispose(): void { if (this.disposed) return; this.disposed = true; this.detach(); this.previous.clear(); this.bridge.dispose?.(); }
  get snapshot(): SemanticSnapshot { return this.snapshotValue; }
  get stats(): Readonly<{ revision: number; nodes: number; bindingSubscription: boolean; actionSubscription: boolean; disposed: boolean }> { return Object.freeze({ revision: this.revision, nodes: this.snapshotValue.nodes.length, bindingSubscription: !!this.bindingSubscription, actionSubscription: !!this.actionSubscription, disposed: this.disposed }); }

  private resolve(value: RuntimeSemanticValue): RuntimeValue { if (value.kind === 'literal') return value.value ?? null; if (!value.binding) throw new InteractionRuntimeError('E_SEMANTICS_RUNTIME_PORT', '$.binding', 'semantic binding identity is missing'); return this.bindingPort.read(value.binding); }
  private attach(): void { this.bindingSubscription = this.bindingPort.subscribe?.(() => this.update()); this.actionSubscription = this.bridge.subscribeActions?.((node, action) => this.perform(node, action)); }
  private detach(): void { this.bindingSubscription?.unsubscribe(); this.actionSubscription?.unsubscribe(); this.bindingSubscription = undefined; this.actionSubscription = undefined; }
  private assertLive(): void { if (this.disposed) throw new InteractionRuntimeError('E_SEMANTICS_RUNTIME_PORT', '$', 'semantics runtime is disposed'); }
}

function freezeNode(value: SemanticSnapshotNode): SemanticSnapshotNode { return Object.freeze(value); }
function boolean(value: RuntimeValue, path: string): boolean { if (typeof value !== 'boolean') throw new InteractionRuntimeError('E_SEMANTICS_RUNTIME_PORT', path, 'expected boolean semantic value'); return value; }
function string(value: RuntimeValue, path: string): string { if (typeof value !== 'string') throw new InteractionRuntimeError('E_SEMANTICS_RUNTIME_PORT', path, 'expected string semantic value'); return value; }
function stringOrNumber(value: RuntimeValue, path: string): string | number { if (typeof value !== 'string' && typeof value !== 'number') throw new InteractionRuntimeError('E_SEMANTICS_RUNTIME_PORT', path, 'expected string or number semantic value'); return value; }
