import { interactionFail } from './diagnostics.js';
import { HYA_INTERACTION_EXTENSION_ID, HYA_INTERACTION_FORMAT, HYA_INTERACTION_VERSION, type HyaInteractionDocument, type InteractionLimits, type InteractionParseOptions } from './types.js';

type Row = Record<string, unknown>;
const DEFAULT_LIMITS: InteractionLimits = Object.freeze({ maxTargets: 250_000, maxListeners: 1_000_000, maxActions: 4_000_000, maxPathDepth: 128, maxEventQueue: 1_000_000, maxEventRecursion: 64, maxPointers: 1_024, maxPolygonPoints: 1_000_000, maxStringBytes: 4 * 1024 * 1024 });

export function parseHyaInteraction(value: unknown, options: InteractionParseOptions = {}): HyaInteractionDocument {
  const limits = { ...DEFAULT_LIMITS, ...options.limits }; for (const [key, item] of Object.entries(limits)) if (!Number.isSafeInteger(item) || item < 1) interactionFail('E_INTERACTION_LIMIT', `$.limits.${key}`, 'limit must be a positive safe integer');
  const root = object(value, '$'); keys(root, ['format', 'version', 'extension', 'dragThreshold', 'targets', 'listeners', 'limits'], '$'); literal(root.format, HYA_INTERACTION_FORMAT, '$.format'); literal(root.version, HYA_INTERACTION_VERSION, '$.version'); literal(root.extension, HYA_INTERACTION_EXTENSION_ID, '$.extension'); nonNegative(root.dragThreshold, '$.dragThreshold');
  if (root.limits !== undefined) { const authored = object(root.limits, '$.limits'); keys(authored, ['maxEventQueue', 'maxEventRecursion', 'maxPointers'], '$.limits'); for (const key of ['maxEventQueue', 'maxEventRecursion', 'maxPointers']) { const result = positiveInteger(authored[key], `$.limits.${key}`); if (result > limits[key as keyof InteractionLimits]) interactionFail('E_INTERACTION_LIMIT', `$.limits.${key}`, 'authored runtime budget exceeds host ceiling'); } }
  const targets = array(root.targets, '$.targets'), listeners = array(root.listeners, '$.listeners'); count(targets.length, limits.maxTargets, '$.targets'); count(listeners.length, limits.maxListeners, '$.listeners'); const targetIds = ids(targets, '$.targets'), listenerIds = ids(listeners, '$.listeners'); void listenerIds; let pointCount = 0, actionCount = 0;
  targets.forEach((candidate, index) => { const path = `$.targets[${index}]`, target = object(candidate, path); keys(target, ['id', 'parent', 'component', 'order', 'transform', 'hitArea', 'clips', 'enabled', 'focusable', 'tabIndex'], path); identifier(target.id, `${path}.id`, limits); optionalReference(target.parent, targetIds, `${path}.parent`); optionalIdentifier(target.component, `${path}.component`, limits); integer(target.order, `${path}.order`); if (target.transform !== undefined) { const transform = tuple(target.transform, 6, `${path}.transform`); if (Math.abs(transform[0]! * transform[3]! - transform[1]! * transform[2]!) < 1e-12) interactionFail('E_INTERACTION_NUMBER', `${path}.transform`, 'transform must be invertible'); } const hit = object(target.hitArea, `${path}.hitArea`), kind = enumeration(hit.kind, ['rect', 'ellipse', 'polygon', 'geometry'], `${path}.hitArea.kind`); if (kind === 'rect') { keys(hit, ['kind', 'rect'], `${path}.hitArea`); const rect = tuple(hit.rect, 4, `${path}.hitArea.rect`); if (rect[2]! < 0 || rect[3]! < 0) interactionFail('E_INTERACTION_NUMBER', `${path}.hitArea.rect`, 'rect size must be non-negative'); } else if (kind === 'ellipse') { keys(hit, ['kind', 'center', 'radius'], `${path}.hitArea`); tuple(hit.center, 2, `${path}.hitArea.center`); const radius = tuple(hit.radius, 2, `${path}.hitArea.radius`); if (radius[0]! < 0 || radius[1]! < 0) interactionFail('E_INTERACTION_NUMBER', `${path}.hitArea.radius`, 'radius must be non-negative'); } else if (kind === 'polygon') { keys(hit, ['kind', 'points'], `${path}.hitArea`); const points = array(hit.points, `${path}.hitArea.points`); if (points.length < 3) interactionFail('E_INTERACTION_FORMAT', `${path}.hitArea.points`, 'polygon requires at least three points'); pointCount += points.length; count(pointCount, limits.maxPolygonPoints, '$.polygonPoints'); points.forEach((point, pointIndex) => tuple(point, 2, `${path}.hitArea.points[${pointIndex}]`)); } else { keys(hit, ['kind', 'port'], `${path}.hitArea`); identifier(hit.port, `${path}.hitArea.port`, limits); } if (target.clips !== undefined) uniqueReferences(target.clips, targetIds, `${path}.clips`); optionalBoolean(target.enabled, `${path}.enabled`); optionalBoolean(target.focusable, `${path}.focusable`); if (target.tabIndex !== undefined) integer(target.tabIndex, `${path}.tabIndex`); });
  validateTargetGraph(targets, limits.maxPathDepth);
  listeners.forEach((candidate, index) => { const path = `$.listeners[${index}]`, listener = object(candidate, path); keys(listener, ['id', 'target', 'event', 'phases', 'pointerButton', 'key', 'keyPhase', 'modifiers', 'gamepad', 'semanticAction', 'actions'], path); identifier(listener.id, `${path}.id`, limits); reference(listener.target, targetIds, `${path}.target`); const event = enumeration(listener.event, ['pointer-enter', 'pointer-exit', 'pointer-move', 'pointer-down', 'pointer-up', 'click', 'drag-start', 'drag', 'drag-end', 'keyboard', 'text-input', 'gamepad', 'focus', 'blur', 'data-change', 'reported-event', 'component-event', 'semantic-action'], `${path}.event`); uniqueEnums(listener.phases, ['capture', 'target', 'bubble'], `${path}.phases`); if (listener.pointerButton !== undefined) integerRange(listener.pointerButton, 0, 31, `${path}.pointerButton`); optionalIdentifier(listener.key, `${path}.key`, limits); optionalEnum(listener.keyPhase, ['down', 'up', 'repeat'], `${path}.keyPhase`); if (listener.modifiers !== undefined) uniqueEnums(listener.modifiers, ['alt', 'control', 'meta', 'shift'], `${path}.modifiers`, true); if (listener.gamepad !== undefined) { const gamepad = object(listener.gamepad, `${path}.gamepad`); keys(gamepad, ['index', 'control', 'phase'], `${path}.gamepad`); if (gamepad.index !== undefined) nonNegativeInteger(gamepad.index, `${path}.gamepad.index`); identifier(gamepad.control, `${path}.gamepad.control`, limits); enumeration(gamepad.phase, ['down', 'up', 'change'], `${path}.gamepad.phase`); } optionalEnum(listener.semanticAction, ['tap', 'increase', 'decrease', 'focus'], `${path}.semanticAction`); if (event === 'keyboard' && listener.key === undefined) interactionFail('E_INTERACTION_FORMAT', `${path}.key`, 'keyboard listener requires key'); if (event === 'gamepad' && listener.gamepad === undefined) interactionFail('E_INTERACTION_FORMAT', `${path}.gamepad`, 'gamepad listener requires descriptor'); if (event === 'semantic-action' && listener.semanticAction === undefined) interactionFail('E_INTERACTION_FORMAT', `${path}.semanticAction`, 'semantic listener requires action'); const actions = array(listener.actions, `${path}.actions`); actionCount += actions.length; count(actionCount, limits.maxActions, '$.actions'); actions.forEach((action, actionIndex) => validateAction(action, `${path}.actions[${actionIndex}]`, targetIds, limits)); });
  assertJson(root, '$', limits.maxPathDepth); return deepFreeze(structuredClone(root) as unknown as HyaInteractionDocument);
}

function validateAction(value: unknown, path: string, targetIds: Set<string>, limits: InteractionLimits): void { const action = object(value, path), kind = enumeration(action.kind, ['data-set', 'data-trigger', 'property-group', 'state-input', 'state-control', 'report-event', 'audio', 'semantic', 'align-target', 'open-url', 'component-input', 'component-event', 'pointer-capture', 'pointer-release', 'focus', 'custom'], `${path}.kind`); const fields: Record<string, readonly string[]> = { 'data-set': ['binding', 'value'], 'data-trigger': ['binding'], 'property-group': ['group'], 'state-input': ['machine', 'input', 'value'], 'state-control': ['machine', 'operation', 'value'], 'report-event': ['name', 'payload'], audio: ['operation', 'target', 'value'], semantic: ['operation', 'target', 'value'], 'align-target': ['target', 'alignment', 'preserveOffset'], 'open-url': ['url', 'target'], 'component-input': ['component', 'input', 'value'], 'component-event': ['component', 'event', 'payload'], 'pointer-capture': [], 'pointer-release': [], focus: ['target'], custom: ['protocol', 'port', 'arguments'] }; keys(action, ['kind', ...fields[kind]!], path); for (const key of ['binding', 'group', 'machine', 'input', 'name', 'target', 'component', 'event', 'protocol', 'port', 'url']) if (action[key] !== undefined) identifier(action[key], `${path}.${key}`, limits); if (kind === 'state-control') enumeration(action.operation, ['play', 'pause', 'resume', 'stop', 'reset'], `${path}.operation`); if (kind === 'audio') enumeration(action.operation, ['play', 'pause', 'stop', 'seek'], `${path}.operation`); if (kind === 'semantic') enumeration(action.operation, ['announce', 'focus', 'increment', 'decrement', 'activate'], `${path}.operation`); if (kind === 'align-target') { reference(action.target, targetIds, `${path}.target`); tuple(action.alignment, 2, `${path}.alignment`); if (typeof action.preserveOffset !== 'boolean') interactionFail('E_INTERACTION_FORMAT', `${path}.preserveOffset`, 'expected boolean'); } if (kind === 'open-url') enumeration(action.target, ['same-context', 'new-context'], `${path}.target`); if (kind === 'focus' && action.target !== undefined) reference(action.target, targetIds, `${path}.target`); for (const key of ['value', 'payload', 'arguments']) if (action[key] !== undefined) assertJson(action[key], `${path}.${key}`, limits.maxPathDepth); }
function validateTargetGraph(values: unknown[], maxDepth: number): void { const parents = new Map<string, string | undefined>(); values.forEach((candidate, index) => { const row = object(candidate, `$.targets[${index}]`); parents.set(row.id as string, row.parent as string | undefined); }); for (const id of parents.keys()) { const seen = new Set<string>(); let current: string | undefined = id, depth = 0; while (current !== undefined) { if (seen.has(current)) interactionFail('E_INTERACTION_GRAPH', '$.targets', `target cycle through ${current}`); if (++depth > maxDepth) interactionFail('E_INTERACTION_LIMIT', '$.targets', 'target depth exceeds budget'); seen.add(current); current = parents.get(current); } } }
function ids(values: unknown[], path: string): Set<string> { const result = new Set<string>(); values.forEach((candidate, index) => { const id = identifier(object(candidate, `${path}[${index}]`).id, `${path}[${index}].id`, DEFAULT_LIMITS); if (result.has(id)) interactionFail('E_INTERACTION_FORMAT', `${path}[${index}].id`, 'duplicate id'); result.add(id); }); return result; }
function uniqueReferences(value: unknown, ids: Set<string>, path: string): void { const seen = new Set<string>(); array(value, path).forEach((entry, index) => { const id = reference(entry, ids, `${path}[${index}]`); if (seen.has(id)) interactionFail('E_INTERACTION_FORMAT', `${path}[${index}]`, 'duplicate reference'); seen.add(id); }); }
function uniqueEnums<T extends string>(value: unknown, allowed: readonly T[], path: string, allowEmpty = false): void { const seen = new Set<T>(), values = array(value, path); if (!allowEmpty && values.length === 0) interactionFail('E_INTERACTION_FORMAT', path, 'list must not be empty'); values.forEach((entry, index) => { const result = enumeration(entry, allowed, `${path}[${index}]`); if (seen.has(result)) interactionFail('E_INTERACTION_FORMAT', `${path}[${index}]`, 'duplicate entry'); seen.add(result); }); }
function assertJson(value: unknown, path: string, maxDepth: number): void { const active = new Set<object>(); const walk = (entry: unknown, current: string, depth: number): void => { if (depth > maxDepth) interactionFail('E_INTERACTION_LIMIT', current, 'value depth exceeds budget'); if (entry === null || typeof entry === 'string' || typeof entry === 'boolean') return; if (typeof entry === 'number') { finite(entry, current); return; } if (!entry || typeof entry !== 'object') interactionFail('E_INTERACTION_FORMAT', current, 'value must be JSON-compatible'); if (active.has(entry)) interactionFail('E_INTERACTION_GRAPH', current, 'cyclic value'); active.add(entry); if (Array.isArray(entry)) entry.forEach((child, index) => walk(child, `${current}[${index}]`, depth + 1)); else for (const [key, child] of Object.entries(entry)) walk(child, `${current}.${key}`, depth + 1); active.delete(entry); }; walk(value, path, 0); }
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); } return value; }
function object(value: unknown, path: string): Row { if (!value || typeof value !== 'object' || Array.isArray(value)) interactionFail('E_INTERACTION_FORMAT', path, 'expected object'); return value as Row; }
function array(value: unknown, path: string): unknown[] { if (!Array.isArray(value)) interactionFail('E_INTERACTION_FORMAT', path, 'expected array'); return value; }
function keys(value: Row, allowed: readonly string[], path: string): void { const set = new Set(allowed); for (const key of Object.keys(value)) if (!set.has(key)) interactionFail('E_INTERACTION_FORMAT', `${path}.${key}`, 'unknown field'); }
function literal(value: unknown, expected: unknown, path: string): void { if (value !== expected) interactionFail('E_INTERACTION_FORMAT', path, `expected ${String(expected)}`); }
function enumeration<T extends string>(value: unknown, allowed: readonly T[], path: string): T { if (typeof value !== 'string' || !allowed.includes(value as T)) interactionFail('E_INTERACTION_FORMAT', path, `expected one of ${allowed.join(', ')}`); return value as T; }
function identifier(value: unknown, path: string, limits: Pick<InteractionLimits, 'maxStringBytes'>): string { if (typeof value !== 'string' || value.length === 0) interactionFail('E_INTERACTION_FORMAT', path, 'expected non-empty string'); if (new TextEncoder().encode(value).length > limits.maxStringBytes) interactionFail('E_INTERACTION_LIMIT', path, 'string exceeds byte budget'); return value; }
function optionalIdentifier(value: unknown, path: string, limits: InteractionLimits): void { if (value !== undefined) identifier(value, path, limits); }
function reference(value: unknown, ids: Set<string>, path: string): string { const id = identifier(value, path, DEFAULT_LIMITS); if (!ids.has(id)) interactionFail('E_INTERACTION_REFERENCE', path, `unknown reference ${id}`); return id; }
function optionalReference(value: unknown, ids: Set<string>, path: string): void { if (value !== undefined) reference(value, ids, path); }
function finite(value: unknown, path: string): number { if (typeof value !== 'number' || !Number.isFinite(value)) interactionFail('E_INTERACTION_NUMBER', path, 'expected finite number'); return value; }
function integer(value: unknown, path: string): number { const result = finite(value, path); if (!Number.isSafeInteger(result)) interactionFail('E_INTERACTION_NUMBER', path, 'expected safe integer'); return result; }
function positiveInteger(value: unknown, path: string): number { const result = integer(value, path); if (result < 1) interactionFail('E_INTERACTION_NUMBER', path, 'expected positive integer'); return result; }
function nonNegativeInteger(value: unknown, path: string): number { const result = integer(value, path); if (result < 0) interactionFail('E_INTERACTION_NUMBER', path, 'expected non-negative integer'); return result; }
function integerRange(value: unknown, min: number, max: number, path: string): number { const result = integer(value, path); if (result < min || result > max) interactionFail('E_INTERACTION_NUMBER', path, `expected ${min}..${max}`); return result; }
function nonNegative(value: unknown, path: string): number { const result = finite(value, path); if (result < 0) interactionFail('E_INTERACTION_NUMBER', path, 'expected non-negative number'); return result; }
function tuple(value: unknown, length: number, path: string): number[] { const result = array(value, path); if (result.length !== length) interactionFail('E_INTERACTION_FORMAT', path, `expected ${length} values`); return result.map((entry, index) => finite(entry, `${path}[${index}]`)); }
function optionalEnum<T extends string>(value: unknown, allowed: readonly T[], path: string): void { if (value !== undefined) enumeration(value, allowed, path); }
function optionalBoolean(value: unknown, path: string): void { if (value !== undefined && typeof value !== 'boolean') interactionFail('E_INTERACTION_FORMAT', path, 'expected boolean'); }
function count(value: number, maximum: number, path: string): void { if (value > maximum) interactionFail('E_INTERACTION_LIMIT', path, `count ${value} exceeds ${maximum}`); }
