import type { Matrix2D, MutableTransform, RuntimeTransform } from './runtime-types.js';

export const IDENTITY_MATRIX: Matrix2D = Object.freeze([1, 0, 0, 1, 0, 0]);
export function mutableTransform(value: RuntimeTransform): MutableTransform { return { x: value.x, y: value.y, rotation: value.rotation, scaleX: value.scaleX, scaleY: value.scaleY, skew: value.skew ?? 0 }; }
export function transformMatrix(value: RuntimeTransform | MutableTransform): Matrix2D { const cosine = Math.cos(value.rotation), sine = Math.sin(value.rotation), skew = value.skew ?? 0, skewCos = Math.cos(value.rotation + Math.PI / 2 + skew), skewSin = Math.sin(value.rotation + Math.PI / 2 + skew); return [cosine * value.scaleX, sine * value.scaleX, skewCos * value.scaleY, skewSin * value.scaleY, value.x, value.y]; }
export function multiplyMatrix(a: ArrayLike<number>, b: ArrayLike<number>): Matrix2D { return [a[0]! * b[0]! + a[2]! * b[1]!, a[1]! * b[0]! + a[3]! * b[1]!, a[0]! * b[2]! + a[2]! * b[3]!, a[1]! * b[2]! + a[3]! * b[3]!, a[0]! * b[4]! + a[2]! * b[5]! + a[4]!, a[1]! * b[4]! + a[3]! * b[5]! + a[5]!]; }
export function invertMatrix(value: ArrayLike<number>): Matrix2D | null { const determinant = value[0]! * value[3]! - value[1]! * value[2]!; if (Math.abs(determinant) < 1e-12) return null; return [value[3]! / determinant, -value[1]! / determinant, -value[2]! / determinant, value[0]! / determinant, (value[2]! * value[5]! - value[3]! * value[4]!) / determinant, (value[1]! * value[4]! - value[0]! * value[5]!) / determinant]; }
export function transformPoint(matrix: ArrayLike<number>, x: number, y: number): readonly [number, number] { return [matrix[0]! * x + matrix[2]! * y + matrix[4]!, matrix[1]! * x + matrix[3]! * y + matrix[5]!]; }
export function decomposeMatrix(matrix: ArrayLike<number>): MutableTransform { const scaleX = Math.hypot(matrix[0]!, matrix[1]!), determinant = matrix[0]! * matrix[3]! - matrix[1]! * matrix[2]!, scaleY = scaleX > 1e-12 ? determinant / scaleX : Math.hypot(matrix[2]!, matrix[3]!), rotation = Math.atan2(matrix[1]!, matrix[0]!), yAxis = Math.atan2(matrix[3]!, matrix[2]!); return { x: matrix[4]!, y: matrix[5]!, rotation, scaleX, scaleY, skew: normalizeAngle(yAxis - rotation - Math.PI / 2) }; }
export function normalizeAngle(value: number): number { let result = (value + Math.PI) % (Math.PI * 2); if (result < 0) result += Math.PI * 2; return result - Math.PI; }
export function mixAngle(from: number, to: number, amount: number): number { return from + normalizeAngle(to - from) * amount; }
export function clamp(value: number, minimum: number, maximum: number): number { return Math.max(minimum, Math.min(maximum, value)); }
export function mix(from: number, to: number, amount: number): number { return from + (to - from) * amount; }
