export type Matrix2D = readonly [number, number, number, number, number, number];
export interface RuntimeTransform { readonly x: number; readonly y: number; readonly rotation: number; readonly scaleX: number; readonly scaleY: number; readonly skew?: number; }
export interface RuntimeParameter { readonly id: string; readonly default: number; readonly min: number; readonly max: number; }
export interface RuntimeBone { readonly id: string; readonly parent?: string; readonly length: number; readonly bind: RuntimeTransform; readonly inverseBind: Matrix2D; }
export interface RuntimeMesh { readonly id: string; readonly positions: ArrayLike<number>; readonly uvs: ArrayLike<number>; readonly indices: ArrayLike<number>; readonly influenceOffsets: ArrayLike<number>; readonly jointIndices: ArrayLike<number>; readonly weights: ArrayLike<number>; }
export interface RuntimeDrawable { readonly id: string; readonly mesh: string; readonly texture?: string; readonly visible?: boolean; readonly solo?: boolean; readonly drawOrder: number; readonly opacity?: number; readonly blendMode?: 'normal' | 'additive' | 'multiplicative'; readonly culling?: boolean; readonly multiplyColor?: readonly [number, number, number, number]; readonly screenColor?: readonly [number, number, number, number]; readonly masks?: readonly string[]; readonly maskMode?: 'alpha' | 'alpha-inverted'; }
export interface RuntimePath { readonly id: string; readonly points: ArrayLike<number>; readonly closed?: boolean; }
export interface RuntimeConstraintBase { readonly id: string; readonly order: number; readonly enabled?: boolean; readonly strength: number; readonly constrained: string; readonly sourceSpace?: 'local' | 'world'; readonly destinationSpace?: 'local' | 'world'; }
export type RuntimeConstraint =
  | RuntimeConstraintBase & { readonly kind: 'ik'; readonly target: string; readonly chainLength: number; readonly invertDirection?: boolean; readonly iterations?: number; readonly tolerance?: number; readonly nonConvergence?: 'error' | 'clamp' }
  | RuntimeConstraintBase & { readonly kind: 'distance'; readonly target: string; readonly distance: number; readonly mode?: 'exact' | 'minimum' | 'maximum' }
  | RuntimeConstraintBase & { readonly kind: 'transform'; readonly target: string; readonly copyFactor?: number; readonly copyFactorY?: number; readonly offset?: RuntimeTransform; readonly min?: RuntimeTransform; readonly max?: RuntimeTransform }
  | RuntimeConstraintBase & { readonly kind: 'translation'; readonly target: string; readonly copyFactor?: number; readonly copyFactorY?: number; readonly offsetX?: number; readonly offsetY?: number; readonly minX?: number; readonly maxX?: number; readonly minY?: number; readonly maxY?: number; readonly limitSpace?: 'local' | 'world' }
  | RuntimeConstraintBase & { readonly kind: 'scale'; readonly target: string; readonly copyFactor?: number; readonly copyFactorY?: number; readonly offsetX?: number; readonly offsetY?: number; readonly minX?: number; readonly maxX?: number; readonly minY?: number; readonly maxY?: number }
  | RuntimeConstraintBase & { readonly kind: 'rotation'; readonly target: string; readonly copyFactor?: number; readonly offset?: number; readonly min?: number; readonly max?: number }
  | RuntimeConstraintBase & { readonly kind: 'follow-path'; readonly path: string; readonly distance: number; readonly distanceEnd?: number; readonly offset?: number; readonly orient?: boolean }
  | RuntimeConstraintBase & { readonly kind: 'scroll'; readonly axis: 'x' | 'y' | 'both'; readonly offsetParameterX?: string; readonly offsetParameterY?: string; readonly percentParameterX?: string; readonly percentParameterY?: string; readonly indexParameter?: string; readonly velocityParameterX?: string; readonly velocityParameterY?: string; readonly activeParameter?: string; readonly viewport: readonly [number, number]; readonly content: readonly [number, number]; readonly infinite?: boolean; readonly virtualize?: boolean; readonly virtualizeBuffer?: number; readonly interactive?: boolean; readonly threshold?: number; readonly dragMultiplier?: number; readonly snap?: number; readonly physics?: { readonly kind: 'clamped' | 'elastic'; readonly friction: number; readonly speedMultiplier: number; readonly elasticFactor?: number; readonly threshold?: number } }
  | RuntimeConstraintBase & { readonly kind: 'scrollbar'; readonly scrollConstraint: string; readonly autoSize?: boolean };
export interface RuntimeDriver { readonly id: string; readonly parameter: string; readonly input: readonly [number, number]; readonly output: readonly [number, number]; readonly clamp?: boolean; readonly mode?: 'replace' | 'add'; readonly target: { readonly kind: 'bone'; readonly id: string; readonly property: 'x' | 'y' | 'rotation' | 'scaleX' | 'scaleY' | 'skew' } | { readonly kind: 'constraint'; readonly id: string; readonly property: 'strength' | 'distance' | 'offset' } | { readonly kind: 'drawable'; readonly id: string; readonly property: 'opacity' | 'drawOrder' | 'visibility' }; }
export interface RuntimeJoystick { readonly id: string; readonly xParameter?: string; readonly yParameter?: string; readonly center: readonly [number, number]; readonly size: readonly [number, number]; readonly origin?: readonly [number, number]; readonly handleDrawable?: string; readonly invertX?: boolean; readonly invertY?: boolean; }
export interface RuntimeRigDefinition { readonly id: string; readonly bones: readonly RuntimeBone[]; readonly meshes: readonly RuntimeMesh[]; readonly drawables: readonly RuntimeDrawable[]; readonly constraints?: readonly RuntimeConstraint[]; readonly paths?: readonly RuntimePath[]; readonly drivers?: readonly RuntimeDriver[]; readonly joysticks?: readonly RuntimeJoystick[]; }
export interface RuntimeRigInstance { readonly id: string; readonly rig: string; readonly parentInstance?: string; readonly parentBone?: string; readonly transform?: RuntimeTransform; readonly parameterMap?: Readonly<Record<string, string>>; }
export interface RuntimeRigDocument { readonly format: 'haiyue-parameterized-rig-2d'; readonly version: 2; readonly extension: 'org.haiyue.deformable-mesh-2d@2'; readonly width: number; readonly height: number; readonly duration?: number; readonly parameters: readonly RuntimeParameter[]; readonly rigs: readonly RuntimeRigDefinition[]; readonly instances: readonly RuntimeRigInstance[]; }

export interface MutableTransform { x: number; y: number; rotation: number; scaleX: number; scaleY: number; skew: number; }
export interface RigBonePose { readonly id: string; readonly parent: number; readonly length: number; readonly inverseBind: Matrix2D; readonly local: MutableTransform; readonly world: Float32Array; }
export interface RigMeshPose { readonly id: string; readonly positions: Float32Array; readonly uvs: ArrayLike<number>; readonly indices: ArrayLike<number>; }
export interface RigDrawablePose { readonly id: string; readonly mesh: string; readonly texture?: string; visible: boolean; drawOrder: number; opacity: number; readonly blendMode: 'normal' | 'additive' | 'multiplicative'; readonly culling: boolean; readonly multiplyColor: readonly [number, number, number, number]; readonly screenColor: readonly [number, number, number, number]; readonly masks: readonly string[]; readonly maskMode: 'alpha' | 'alpha-inverted'; }
export interface EvaluatedRigPose { readonly instanceId: string; readonly rigId: string; readonly parameters: ReadonlyMap<string, number>; readonly bones: readonly RigBonePose[]; readonly meshes: readonly RigMeshPose[]; readonly drawables: readonly RigDrawablePose[]; readonly constraintOrder: readonly string[]; }
export interface EvaluatedRigDocument { readonly time: number; readonly instances: ReadonlyMap<string, EvaluatedRigPose>; }
export interface RigParameterLayer { readonly id: string; readonly weight: number; readonly mode?: 'override' | 'additive'; readonly values: Readonly<Record<string, number>>; }
export interface RigEvaluateOptions { readonly time: number; readonly loop?: boolean; readonly parameters?: Readonly<Record<string, number>>; readonly layers?: readonly RigParameterLayer[]; readonly joysticks?: Readonly<Record<string, readonly [number, number]>>; }
