import {
  cleanOutputDirectory,
  haiyueExternal,
  haiyuePlugins,
  libraryOutput,
} from '../config/rollup.shared.js';

export default {
  input: {
    index: 'src/index.ts',
    experimental: 'src/experimental.ts',
    'experimental/assets': 'src/experimental/assets.ts',
    'experimental/async': 'src/experimental/async.ts',
    'experimental/ktx2-worker-runtime': 'src/experimental/ktx2-worker-runtime.ts',
    'experimental/diagnostics': 'src/experimental/diagnostics.ts',
    'experimental/gpu-driven': 'src/experimental/gpu-driven.ts',
    'experimental/renderer': 'src/experimental/renderer.ts',
    core: 'src/core.ts',
    assets: 'src/assets.ts',
    diagnostics: 'src/diagnostics.ts',
    'extension-authoring': 'src/extension-authoring.ts',
    ecs: 'src/ecs.ts',
    components: 'src/components.ts',
    geometry: 'src/geometry.ts',
    material: 'src/material.ts',
    systems: 'src/systems.ts',
    physics: 'src/physics.ts',
    'physics-components': 'src/physics-components.ts',
    'physics/backend': 'src/physics/backend.ts',
    postprocess: 'src/postprocess.ts',
    gui: 'src/gui.ts',
    compute: 'src/compute.ts',
    scene: 'src/scene.ts',
    input: 'src/input.ts',
    controls: 'src/controls.ts',
    tween: 'src/tween.ts',
    rtt: 'src/rtt.ts',
    font: 'src/font.ts',
    color: 'src/color.ts',
    lighting: 'src/lighting.ts',
    math: 'src/math.ts',
    serialization: 'src/serialization.ts',
    save: 'src/save.ts',
    renderer: 'src/renderer.ts',
    navigation: 'src/navigation.ts',
    'internal/precompiled-shader-runtime': 'src/shader/PrecompiledShaderRuntime.ts',
    'internal/postprocess-shader-artifact': 'src/shaders/generated/postprocess-builtins-artifact.generated.ts',
    'internal/2d-ui-shader-artifact': 'src/shaders/generated/2d-ui-artifact.generated.ts',
    'internal/simple3d-shader-artifact': 'src/shaders/generated/simple3d-artifact.generated.ts',
    'internal/deformation-shader-artifact': 'src/shaders/generated/deformation-artifact.generated.ts',
    'internal/material-lighting-shader-artifact': 'src/shaders/generated/material-lighting-artifact.generated.ts',
    'internal/specialized-rendering-shader-artifact': 'src/shaders/generated/specialized-rendering-artifact.generated.ts',
    'internal/compute-shader-artifact': 'src/shaders/generated/compute-artifact.generated.ts',
  },
  output: libraryOutput(),
  external: haiyueExternal(),
  plugins: [cleanOutputDirectory(), ...haiyuePlugins()],
};
