export type RuntimeColor = readonly [number, number, number, number];
export type RuntimePaintSource = { readonly kind: 'solid'; readonly color: RuntimeColor } | { readonly kind: 'linear-gradient'; readonly start: readonly [number, number]; readonly end: readonly [number, number]; readonly stops: readonly { readonly offset: number; readonly color: RuntimeColor }[] } | { readonly kind: 'radial-gradient'; readonly center: readonly [number, number]; readonly radius: number; readonly stops: readonly { readonly offset: number; readonly color: RuntimeColor }[] };
export interface RuntimeGlyphMetric { readonly glyphId: number; readonly advance: number; readonly bounds: readonly [number, number, number, number]; readonly axisAdvance?: Readonly<Record<string, number>>; }
export interface RuntimeFontMetrics { readonly unitsPerEm: number; readonly ascent: number; readonly descent: number; readonly lineGap: number; readonly missingGlyph: RuntimeGlyphMetric; readonly glyphs: Readonly<Record<string, RuntimeGlyphMetric>>; readonly ligatures?: Readonly<Record<string, RuntimeGlyphMetric>>; readonly kerning?: Readonly<Record<string, number>>; readonly axes?: Readonly<Record<string, { readonly min: number; readonly default: number; readonly max: number }>>; }
export interface RuntimeFontAsset { readonly id: string; readonly kind: 'font'; readonly family: string; readonly weight: number; readonly style: 'normal' | 'italic'; readonly metrics: RuntimeFontMetrics; readonly source: { readonly integrity?: string }; }
export interface RuntimeTextStyle { readonly id: string; readonly fontAssets: readonly string[]; readonly fontFamily: string; readonly fontWeight: number; readonly fontStyle: 'normal' | 'italic'; readonly fontSize: number; readonly lineHeight: number; readonly tracking: number; readonly alignment: 'start' | 'center' | 'end' | 'justify'; readonly verticalAlignment?: 'top' | 'middle' | 'bottom' | 'baseline'; readonly direction?: 'auto' | 'ltr' | 'rtl'; readonly language?: string; readonly script?: string; readonly axes?: Readonly<Record<string, number>>; readonly features?: Readonly<Record<string, boolean | number>>; readonly fills: readonly { readonly source: RuntimePaintSource; readonly opacity?: number }[]; readonly strokes?: readonly { readonly source: RuntimePaintSource; readonly width: number; readonly opacity?: number; readonly join?: 'miter' | 'round' | 'bevel' }[]; readonly background?: { readonly color: RuntimeColor; readonly cornerRadius?: number }; }
export interface RuntimeTextRun { readonly id: string; readonly style: string; readonly text: string; readonly valuePort?: string; }
export interface RuntimeModifierRange { readonly start: number; readonly end: number; readonly units: 'grapheme' | 'word' | 'line' | 'percent'; readonly falloffFrom?: number; readonly falloffTo?: number; readonly increment?: number; readonly offset?: number; readonly mode?: 'clamp' | 'repeat' | 'mirror'; readonly strength?: number; }
export type RuntimeTextModifier = { readonly kind: 'transform'; readonly range: RuntimeModifierRange; readonly translation?: readonly [number, number]; readonly scale?: readonly [number, number]; readonly rotation?: number; readonly origin?: readonly [number, number]; readonly opacity?: number; readonly variables?: Readonly<Record<string, number>> } | { readonly kind: 'follow-path'; readonly range: RuntimeModifierRange; readonly points: readonly number[]; readonly radial?: boolean; readonly orient?: boolean; readonly start?: number; readonly end?: number; readonly offset?: number };
export interface RuntimeTextBlock { readonly id: string; readonly runs: readonly RuntimeTextRun[]; readonly width: number; readonly height: number; readonly wrap?: 'none' | 'word' | 'grapheme'; readonly overflow?: 'visible' | 'clip' | 'ellipsis'; readonly paragraphSpacing?: number; readonly origin?: readonly [number, number]; readonly verticalTrim?: { readonly top: number; readonly bottom: number }; readonly modifiers?: readonly RuntimeTextModifier[]; readonly input?: { readonly valuePort: string; readonly selectionPort?: string; readonly cursorPort?: string; readonly multiline?: boolean; readonly selectionRadius?: number }; }
export interface RuntimeTextDocument { readonly shaping: { readonly stack: string; readonly backendRevision: string; readonly unicodeVersion: string; readonly graphemeRevision: string; readonly bidiRevision: string }; readonly assets: readonly ({ readonly id: string; readonly kind: string } | RuntimeFontAsset)[]; readonly textStyles: readonly RuntimeTextStyle[]; readonly textBlocks: readonly RuntimeTextBlock[]; }

export interface TextEvaluateUpdates { readonly strings?: Readonly<Record<string, string>>; readonly selections?: Readonly<Record<string, readonly [number, number]>>; readonly cursors?: Readonly<Record<string, number>>; }
export interface ShapedGlyph { readonly glyphId: number; readonly sequence: string; readonly logicalIndex: number; readonly direction: 'ltr' | 'rtl'; readonly fontAsset: string; readonly style: RuntimeTextStyle; readonly advance: number; readonly bounds: readonly [number, number, number, number]; readonly axes: Readonly<Record<string, number>>; readonly breakClass: 'none' | 'space' | 'newline'; }
export interface TextGlyphPose { readonly glyphId: number; readonly sequence: string; readonly logicalIndex: number; readonly line: number; readonly fontAsset: string; readonly x: number; readonly y: number; readonly width: number; readonly height: number; readonly advance: number; readonly rotation: number; readonly scaleX: number; readonly scaleY: number; readonly opacity: number; readonly axes: Readonly<Record<string, number>>; readonly fills: RuntimeTextStyle['fills']; readonly strokes: NonNullable<RuntimeTextStyle['strokes']>; }
export interface TextLinePose { readonly index: number; readonly startGlyph: number; readonly endGlyph: number; readonly x: number; readonly y: number; readonly width: number; readonly height: number; }
export interface TextSelectionPose { readonly kind: 'selection' | 'cursor'; readonly x: number; readonly y: number; readonly width: number; readonly height: number; readonly radius: number; }
export interface TextBlockPose { readonly id: string; readonly width: number; readonly height: number; readonly contentWidth: number; readonly contentHeight: number; readonly glyphs: readonly TextGlyphPose[]; readonly lines: readonly TextLinePose[]; readonly controls: readonly TextSelectionPose[]; }
export interface TextRuntimeLimits { readonly maxGlyphs: number; readonly maxLines: number; }
