import { RenderGraph } from '@haiyue/engine/experimental';
import type { RayHybridFrameContract, RayHybridPass } from './types.js';
export function createRayHybridRenderPlan(contract: RayHybridFrameContract): readonly RayHybridPass[] {
  if (contract.status === 'failed') throw new Error('RAY_HYBRID_CONTRACT_FAILED'); if (contract.status === 'bypassed') return Object.freeze([]);
  const graph = new RenderGraph<RayHybridPass, string>(); const raster = graph.addResource({ name: 'ray.hybrid.borrowed-raster', payload: 'raster', transient: false }); const facts = graph.addResource({ name: 'ray.hybrid.uploaded-facts', payload: 'facts', transient: true });
  const outputs = new Map<string, ReturnType<typeof graph.addResource>>(); const uploadPayload = Object.freeze({ kind: 'upload', label: 'ray.hybrid.upload', enabled: true }) as RayHybridPass; const upload = graph.addPass({ name: uploadPayload.label, passClass: 'view-local', payload: uploadPayload }); graph.write(upload, facts); const enabledPasses = [];
  for (const effect of ['shadow', 'reflection', 'ao'] as const) { if (!contract.effects[effect].enabled) continue; const output = graph.addResource({ name: `ray.hybrid.${effect}.output`, payload: effect, transient: true }); outputs.set(effect, output); const payload = Object.freeze({ kind: effect, label: `ray.hybrid.${effect}`, enabled: true }) as RayHybridPass; const pass = graph.addPass({ name: payload.label, passClass: 'view-local', payload }); graph.read(pass, facts); graph.read(pass, raster); graph.write(pass, output); graph.dependsOn(pass, upload); enabledPasses.push(pass); }
  const composed = graph.addResource({ name: 'ray.hybrid.composite.output', payload: 'composite', transient: false }); const compositePayload = Object.freeze({ kind: 'composite', label: 'ray.hybrid.composite', enabled: true }) as RayHybridPass; const composite = graph.addPass({ name: compositePayload.label, passClass: 'view-local', payload: compositePayload }); graph.read(composite, raster); for (const output of outputs.values()) graph.read(composite, output); for (const pass of enabledPasses) graph.dependsOn(composite, pass); graph.write(composite, composed);
  const consumerPayload = Object.freeze({ kind: 'consumer', label: 'ray.hybrid.consumer', enabled: true }) as RayHybridPass; const consumer = graph.addPass({ name: consumerPayload.label, passClass: 'view-local', payload: consumerPayload, sideEffect: true }); graph.read(consumer, composed); graph.dependsOn(consumer, composite); return Object.freeze(graph.compile().map(pass => pass.payload));
}
