export type RuntimeBlendMode = 'normal' | 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten' | 'color-dodge' | 'color-burn' | 'hard-light' | 'soft-light' | 'difference' | 'exclusion' | 'hue' | 'saturation' | 'color' | 'luminosity' | 'add' | 'subtract';
export type RuntimeColor = readonly [number, number, number, number];
export type RuntimePoint = readonly [number, number];

export interface RuntimePathFrame { readonly time: number; readonly commands: string; readonly values: readonly number[]; }
export interface RuntimePathGeometry { readonly kind: 'path'; readonly commands: string; readonly values: readonly number[]; readonly fillRule?: 'nonzero' | 'evenodd'; readonly isHole?: boolean; readonly topologyPolicy?: 'stable' | 'discrete'; readonly frames?: readonly RuntimePathFrame[]; }
export interface RuntimeEllipseGeometry { readonly kind: 'ellipse'; readonly cx: number; readonly cy: number; readonly rx: number; readonly ry: number; }
export interface RuntimeRectangleGeometry { readonly kind: 'rectangle'; readonly x: number; readonly y: number; readonly width: number; readonly height: number; readonly radii?: readonly [number, number, number, number]; }
export interface RuntimePolygonGeometry { readonly kind: 'polygon'; readonly cx: number; readonly cy: number; readonly radius: number; readonly points: number; readonly rotation?: number; readonly cornerRadius?: number; }
export interface RuntimeStarGeometry { readonly kind: 'star'; readonly cx: number; readonly cy: number; readonly outerRadius: number; readonly innerRadius: number; readonly points: number; readonly rotation?: number; readonly cornerRadius?: number; }
export interface RuntimeTriangleGeometry { readonly kind: 'triangle'; readonly points: readonly [number, number, number, number, number, number]; readonly cornerRadius?: number; }
export interface RuntimeImageGeometry { readonly kind: 'image'; readonly resource: string; readonly x: number; readonly y: number; readonly width: number; readonly height: number; readonly crop?: readonly [number, number, number, number]; readonly fit?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down'; readonly alignment?: RuntimePoint; readonly mesh?: { readonly positions: readonly number[]; readonly uvs: readonly number[]; readonly indices: readonly number[] }; }
export interface RuntimeNSliceGeometry { readonly kind: 'n-slice'; readonly source: { readonly kind: 'image'; readonly resource: string } | { readonly kind: 'node'; readonly node: string }; readonly x: number; readonly y: number; readonly width: number; readonly height: number; readonly sourceSize: RuntimePoint; readonly xCuts: readonly number[]; readonly yCuts: readonly number[]; }
export type RuntimeGeometry = RuntimePathGeometry | RuntimeEllipseGeometry | RuntimeRectangleGeometry | RuntimePolygonGeometry | RuntimeStarGeometry | RuntimeTriangleGeometry | RuntimeImageGeometry | RuntimeNSliceGeometry;

export interface RuntimeGradientStop { readonly offset: number; readonly color: RuntimeColor; }
export type RuntimePaintSource = { readonly kind: 'solid'; readonly color: RuntimeColor } | { readonly kind: 'linear-gradient'; readonly start: RuntimePoint; readonly end: RuntimePoint; readonly stops: readonly RuntimeGradientStop[]; readonly colorSpace?: string } | { readonly kind: 'radial-gradient'; readonly center: RuntimePoint; readonly radius: number; readonly focal?: RuntimePoint; readonly stops: readonly RuntimeGradientStop[]; readonly colorSpace?: string };
export type RuntimePaint =
  | { readonly kind: 'fill'; readonly source: RuntimePaintSource; readonly fillRule?: 'nonzero' | 'evenodd'; readonly opacity?: number; readonly blendMode?: RuntimeBlendMode; readonly visible?: boolean }
  | { readonly kind: 'stroke'; readonly source: RuntimePaintSource; readonly width: number; readonly cap?: 'butt' | 'round' | 'square'; readonly join?: 'miter' | 'round' | 'bevel'; readonly miterLimit?: number; readonly dash?: readonly number[]; readonly dashOffset?: number; readonly dashUnits?: 'absolute' | 'path-percent'; readonly trim?: { readonly start: number; readonly end: number; readonly offset?: number; readonly mode?: 'simultaneous' | 'individual' }; readonly transformMode?: 'scale' | 'fixed'; readonly opacity?: number; readonly blendMode?: RuntimeBlendMode; readonly visible?: boolean };
export type RuntimeEffect =
  | { readonly kind: 'feather'; readonly radiusX: number; readonly radiusY: number; readonly offsetX?: number; readonly offsetY?: number; readonly inner?: boolean; readonly space?: 'local' | 'world' }
  | { readonly kind: 'opacity'; readonly value: number }
  | { readonly kind: 'color-matrix'; readonly values: readonly number[] }
  | { readonly kind: 'blur'; readonly radiusX: number; readonly radiusY: number }
  | { readonly kind: 'drop-shadow'; readonly offsetX: number; readonly offsetY: number; readonly blur: number; readonly color: RuntimeColor }
  | { readonly kind: 'custom-path-port'; readonly port: string; readonly inputs: Readonly<Record<string, number | boolean | string>>; readonly execution: 'external-only' };
export interface RuntimeEffectGroup { readonly id: string; readonly target?: string; readonly blendMode?: RuntimeBlendMode; readonly effects: readonly RuntimeEffect[]; }
export interface RuntimeClip { readonly id: string; readonly source: string; readonly operation?: 'add' | 'subtract' | 'intersect' | 'difference'; readonly inverted?: boolean; readonly fillRule?: 'nonzero' | 'evenodd'; readonly children?: readonly string[]; }
export interface RuntimeNode { readonly id: string; readonly visible?: boolean; readonly solo?: boolean; readonly drawOrder: number; readonly opacity?: number; readonly transform?: readonly [number, number, number, number, number, number]; readonly geometries: readonly RuntimeGeometry[]; readonly paints: readonly RuntimePaint[]; readonly effectGroups?: readonly RuntimeEffectGroup[]; readonly clips?: readonly string[]; }
export interface RuntimeImageResource { readonly id: string; readonly kind: 'image'; readonly width: number; readonly height: number; readonly source: unknown; readonly colorSpace?: string; readonly filter?: 'nearest' | 'linear'; readonly wrapX?: string; readonly wrapY?: string; }
export interface RuntimeVectorDocument { readonly format: 'haiyue-vector-visual'; readonly version: 1; readonly width: number; readonly height: number; readonly duration?: number; readonly resources: readonly RuntimeImageResource[]; readonly nodes: readonly RuntimeNode[]; readonly clips: readonly RuntimeClip[]; }

export interface RuntimeContour { readonly points: readonly RuntimePoint[]; readonly closed: boolean; readonly isHole: boolean; }
export interface RuntimeGeometryResult { readonly contours: readonly RuntimeContour[]; readonly image?: RuntimeImageGeometry | RuntimeNSliceGeometry; }
export interface RuntimeDrawOperation { readonly nodeId: string; readonly geometryIndex: number; readonly paintIndex: number; readonly drawOrder: number; readonly opacity: number; readonly transform: readonly [number, number, number, number, number, number]; readonly geometry: RuntimeGeometryResult; readonly paint: RuntimePaint; readonly clips: readonly string[]; readonly effectGroups: readonly RuntimeEffectGroup[]; }
export interface RuntimeDrawPlan { readonly time: number; readonly width: number; readonly height: number; readonly deviceGeneration: number; readonly operations: readonly RuntimeDrawOperation[]; readonly clips: ReadonlyMap<string, RuntimeClip>; readonly resources: ReadonlyMap<string, RuntimeImageResource>; readonly nodeGeometry: ReadonlyMap<string, readonly RuntimeGeometryResult[]>; readonly nodeTransforms: ReadonlyMap<string, readonly [number, number, number, number, number, number]>; }

export interface VectorRuntimeStats { readonly geometryEntries: number; readonly paintEntries: number; readonly targetEntries: number; readonly retiredEntries: number; readonly deviceGeneration: number; readonly disposed: boolean; }
