// Authoritative ray traversal module. The checked-in Artifact V2 module is generated by
// scripts/verify-ray-traversal-shader.mjs; runtime code never parses or concatenates WGSL.

const LEAF_BIT: u32 = 0x80000000u;
const INDEX_MASK: u32 = 0x7fffffffu;
const MISSING: u32 = 0xffffffffu;
const STACK_CAPACITY: u32 = 64u;
const HIT_WORDS: u32 = 24u;
const MAX_DISTANCE: f32 = 3.402823466e+38;

struct TraversalParams { rayCount: u32, rayOffset: u32, outputOffset: u32, mode: u32, tlasRoot: u32, stackLimit: u32, instanceCount: u32, reserved: u32 }
struct TraversalDiagnostics { rays: atomic<u32>, tlasNodeTests: atomic<u32>, blasNodeTests: atomic<u32>, primitiveTests: atomic<u32>, hits: atomic<u32>, misses: atomic<u32>, stackOverflows: atomic<u32>, invalidAccesses: atomic<u32> }
struct Candidate { hit: u32, t: f32, barycentric: vec3f, kind: u32, geometryIndex: u32, primitiveIndex: u32, frontFace: u32, position: vec3f, normal: vec3f }

@group(0) @binding(0) var<uniform> params: TraversalParams;
@group(0) @binding(1) var<storage, read> rays: array<u32>;
@group(0) @binding(2) var<storage, read> blasNodes: array<u32>;
@group(0) @binding(3) var<storage, read> blasTable: array<u32>;
@group(0) @binding(4) var<storage, read> tlasNodes: array<u32>;
@group(0) @binding(5) var<storage, read> primitives: array<u32>;
@group(0) @binding(6) var<storage, read> instances: array<u32>;
@group(0) @binding(7) var<storage, read_write> hits: array<u32>;
@group(0) @binding(8) var<storage, read_write> diagnostics: TraversalDiagnostics;

fn ray_f32(rayIndex: u32, word: u32) -> f32 { return bitcast<f32>(rays[rayIndex * 8u + word]); }
fn instance_f32(instanceIndex: u32, word: u32) -> f32 { return bitcast<f32>(instances[instanceIndex * 36u + word]); }

fn transform_point(instanceIndex: u32, value: vec3f, inverse: bool) -> vec3f {
  let base = select(0u, 16u, inverse);
  let x = instance_f32(instanceIndex, base) * value.x + instance_f32(instanceIndex, base + 4u) * value.y + instance_f32(instanceIndex, base + 8u) * value.z + instance_f32(instanceIndex, base + 12u);
  let y = instance_f32(instanceIndex, base + 1u) * value.x + instance_f32(instanceIndex, base + 5u) * value.y + instance_f32(instanceIndex, base + 9u) * value.z + instance_f32(instanceIndex, base + 13u);
  let z = instance_f32(instanceIndex, base + 2u) * value.x + instance_f32(instanceIndex, base + 6u) * value.y + instance_f32(instanceIndex, base + 10u) * value.z + instance_f32(instanceIndex, base + 14u);
  let w = instance_f32(instanceIndex, base + 3u) * value.x + instance_f32(instanceIndex, base + 7u) * value.y + instance_f32(instanceIndex, base + 11u) * value.z + instance_f32(instanceIndex, base + 15u);
  return vec3f(x, y, z) / select(w, 1.0, w == 0.0);
}

fn transform_vector(instanceIndex: u32, value: vec3f, inverse: bool) -> vec3f {
  let base = select(0u, 16u, inverse);
  return vec3f(
    instance_f32(instanceIndex, base) * value.x + instance_f32(instanceIndex, base + 4u) * value.y + instance_f32(instanceIndex, base + 8u) * value.z,
    instance_f32(instanceIndex, base + 1u) * value.x + instance_f32(instanceIndex, base + 5u) * value.y + instance_f32(instanceIndex, base + 9u) * value.z,
    instance_f32(instanceIndex, base + 2u) * value.x + instance_f32(instanceIndex, base + 6u) * value.y + instance_f32(instanceIndex, base + 10u) * value.z);
}

fn transform_normal(instanceIndex: u32, value: vec3f) -> vec3f {
  return normalize(vec3f(
    instance_f32(instanceIndex, 16u) * value.x + instance_f32(instanceIndex, 17u) * value.y + instance_f32(instanceIndex, 18u) * value.z,
    instance_f32(instanceIndex, 20u) * value.x + instance_f32(instanceIndex, 21u) * value.y + instance_f32(instanceIndex, 22u) * value.z,
    instance_f32(instanceIndex, 24u) * value.x + instance_f32(instanceIndex, 25u) * value.y + instance_f32(instanceIndex, 26u) * value.z));
}

fn intersects_bounds(origin: vec3f, direction: vec3f, tMin: f32, tMax: f32, minimum: vec3f, maximum: vec3f) -> bool {
  var low = tMin;
  var high = tMax;
  for (var axis = 0u; axis < 3u; axis++) {
    let component = direction[axis];
    if (abs(component) <= 1e-20) {
      if (origin[axis] < minimum[axis] || origin[axis] > maximum[axis]) { return false; }
    } else {
      let inverse = 1.0 / component;
      let first = (minimum[axis] - origin[axis]) * inverse;
      let second = (maximum[axis] - origin[axis]) * inverse;
      low = max(low, min(first, second));
      high = min(high, max(first, second));
      if (low > high) { return false; }
    }
  }
  return true;
}

fn tlas_bounds_hit(nodeIndex: u32, origin: vec3f, direction: vec3f, tMin: f32, tMax: f32) -> bool {
  let base = nodeIndex * 8u;
  return intersects_bounds(origin, direction, tMin, tMax,
    vec3f(bitcast<f32>(tlasNodes[base]), bitcast<f32>(tlasNodes[base + 1u]), bitcast<f32>(tlasNodes[base + 2u])),
    vec3f(bitcast<f32>(tlasNodes[base + 4u]), bitcast<f32>(tlasNodes[base + 5u]), bitcast<f32>(tlasNodes[base + 6u])));
}
fn blas_bounds_hit(nodeIndex: u32, origin: vec3f, direction: vec3f, tMin: f32, tMax: f32) -> bool {
  let base = nodeIndex * 8u;
  return intersects_bounds(origin, direction, tMin, tMax,
    vec3f(bitcast<f32>(blasNodes[base]), bitcast<f32>(blasNodes[base + 1u]), bitcast<f32>(blasNodes[base + 2u])),
    vec3f(bitcast<f32>(blasNodes[base + 4u]), bitcast<f32>(blasNodes[base + 5u]), bitcast<f32>(blasNodes[base + 6u])));
}

fn empty_candidate() -> Candidate { return Candidate(0u, MAX_DISTANCE, vec3f(0.0), MISSING, MISSING, MISSING, 0u, vec3f(0.0), vec3f(0.0)); }

fn triangle_candidate(primitiveIndex: u32, instanceIndex: u32, origin: vec3f, direction: vec3f, tMin: f32, tMax: f32) -> Candidate {
  let base = primitiveIndex * 16u;
  let p0 = transform_point(instanceIndex, vec3f(bitcast<f32>(primitives[base]), bitcast<f32>(primitives[base + 1u]), bitcast<f32>(primitives[base + 2u])), false);
  let p1 = transform_point(instanceIndex, vec3f(bitcast<f32>(primitives[base + 3u]), bitcast<f32>(primitives[base + 4u]), bitcast<f32>(primitives[base + 5u])), false);
  let p2 = transform_point(instanceIndex, vec3f(bitcast<f32>(primitives[base + 6u]), bitcast<f32>(primitives[base + 7u]), bitcast<f32>(primitives[base + 8u])), false);
  let edge1 = p1 - p0;
  let edge2 = p2 - p0;
  let winding = cross(edge1, edge2);
  let scale = max(dot(edge1, edge1) * dot(edge2, edge2), 1.0);
  if (dot(winding, winding) <= 1e-24 * scale) { return empty_candidate(); }
  let pvec = cross(direction, edge2);
  let determinant = dot(edge1, pvec);
  if (abs(determinant) <= 1e-12 * max(length(edge1) * length(edge2), 1.0)) { return empty_candidate(); }
  let inverseDeterminant = 1.0 / determinant;
  let tvec = origin - p0;
  let u = dot(tvec, pvec) * inverseDeterminant;
  if (u < -1e-6 || u > 1.0 + 1e-6) { return empty_candidate(); }
  let qvec = cross(tvec, edge1);
  let v = dot(direction, qvec) * inverseDeterminant;
  if (v < -1e-6 || u + v > 1.0 + 1e-6) { return empty_candidate(); }
  let t = dot(edge2, qvec) * inverseDeterminant;
  let rangeEpsilon = 1e-6 * max(1.0, abs(t));
  if (t < tMin - rangeEpsilon || t > tMax + rangeEpsilon) { return empty_candidate(); }
  let normal = normalize(winding);
  let frontFace = select(0u, 1u, dot(direction, normal) < 0.0);
  return Candidate(1u, t, vec3f(1.0 - u - v, u, v), 0u, primitives[base + 14u], primitives[base + 13u], frontFace, origin + direction * t, normal);
}

fn sphere_candidate(primitiveIndex: u32, instanceIndex: u32, origin: vec3f, direction: vec3f, tMin: f32, tMax: f32) -> Candidate {
  let base = primitiveIndex * 16u;
  let localOrigin = transform_point(instanceIndex, origin, true);
  let localDirection = transform_vector(instanceIndex, direction, true);
  let center = vec3f(bitcast<f32>(primitives[base]), bitcast<f32>(primitives[base + 1u]), bitcast<f32>(primitives[base + 2u]));
  let radius = bitcast<f32>(primitives[base + 3u]);
  let offset = localOrigin - center;
  let a = dot(localDirection, localDirection);
  let halfB = dot(offset, localDirection);
  let c = dot(offset, offset) - radius * radius;
  let discriminant = halfB * halfB - a * c;
  if (discriminant < 0.0 || a <= 1e-12) { return empty_candidate(); }
  let root = sqrt(max(0.0, discriminant));
  var t = (-halfB - root) / a;
  var rangeEpsilon = 1e-6 * max(1.0, abs(t));
  if (t < tMin - rangeEpsilon || t > tMax + rangeEpsilon) {
    t = (-halfB + root) / a;
    rangeEpsilon = 1e-6 * max(1.0, abs(t));
    if (t < tMin - rangeEpsilon || t > tMax + rangeEpsilon) { return empty_candidate(); }
  }
  let localPosition = localOrigin + localDirection * t;
  let normal = transform_normal(instanceIndex, normalize(localPosition - center));
  let frontFace = select(0u, 1u, dot(direction, normal) < 0.0);
  return Candidate(1u, t, vec3f(0.0), 1u, primitives[base + 14u], primitives[base + 13u], frontFace, origin + direction * t, normal);
}

fn write_empty(outputIndex: u32, flags: u32) {
  let base = outputIndex * HIT_WORDS;
  hits[base] = bitcast<u32>(MAX_DISTANCE);
  for (var word = 1u; word < HIT_WORDS; word++) { hits[base + word] = 0u; }
  hits[base + 3u] = MISSING; hits[base + 4u] = MISSING; hits[base + 5u] = MISSING; hits[base + 6u] = MISSING; hits[base + 7u] = flags;
}
fn write_candidate(outputIndex: u32, candidate: Candidate, instanceIdentity: u32) {
  let base = outputIndex * HIT_WORDS;
  hits[base] = bitcast<u32>(candidate.t); hits[base + 1u] = bitcast<u32>(candidate.barycentric.y); hits[base + 2u] = bitcast<u32>(candidate.barycentric.z);
  hits[base + 3u] = candidate.kind; hits[base + 4u] = instanceIdentity; hits[base + 5u] = candidate.geometryIndex; hits[base + 6u] = candidate.primitiveIndex;
  hits[base + 7u] = 1u | (candidate.frontFace << 1u);
  hits[base + 8u] = bitcast<u32>(candidate.position.x); hits[base + 9u] = bitcast<u32>(candidate.position.y); hits[base + 10u] = bitcast<u32>(candidate.position.z); hits[base + 11u] = 0u;
  hits[base + 12u] = bitcast<u32>(candidate.normal.x); hits[base + 13u] = bitcast<u32>(candidate.normal.y); hits[base + 14u] = bitcast<u32>(candidate.normal.z); hits[base + 15u] = 0u;
  hits[base + 16u] = hits[base + 12u]; hits[base + 17u] = hits[base + 13u]; hits[base + 18u] = hits[base + 14u]; hits[base + 19u] = 0u;
  let facing = select(-candidate.normal, candidate.normal, candidate.frontFace != 0u);
  hits[base + 20u] = bitcast<u32>(facing.x); hits[base + 21u] = bitcast<u32>(facing.y); hits[base + 22u] = bitcast<u32>(facing.z); hits[base + 23u] = 0u;
}

@compute @workgroup_size(64, 1, 1)
fn cs_main(@builtin(global_invocation_id) globalId: vec3u) {
  if (globalId.x >= params.rayCount) { return; }
  let rayIndex = params.rayOffset + globalId.x;
  let outputIndex = params.outputOffset + globalId.x;
  write_empty(outputIndex, 0u);
  atomicAdd(&diagnostics.rays, 1u);
  if (rayIndex * 8u + 7u >= arrayLength(&rays) || outputIndex * HIT_WORDS + HIT_WORDS > arrayLength(&hits)) { atomicAdd(&diagnostics.invalidAccesses, 1u); write_empty(outputIndex, 8u); return; }
  let origin = vec3f(ray_f32(rayIndex, 0u), ray_f32(rayIndex, 1u), ray_f32(rayIndex, 2u));
  let tMin = ray_f32(rayIndex, 3u);
  let direction = vec3f(ray_f32(rayIndex, 4u), ray_f32(rayIndex, 5u), ray_f32(rayIndex, 6u));
  let tMax = ray_f32(rayIndex, 7u);
  if (params.tlasRoot == MISSING) { atomicAdd(&diagnostics.misses, 1u); return; }

  var stack: array<u32, 64>;
  var stackSize = 1u;
  stack[0] = params.tlasRoot;
  var best = empty_candidate();
  var bestInstanceIdentity = MISSING;
  loop {
    if (stackSize == 0u) { break; }
    stackSize--;
    let tlasNodeIndex = stack[stackSize];
    if (tlasNodeIndex * 8u + 7u >= arrayLength(&tlasNodes)) { atomicAdd(&diagnostics.invalidAccesses, 1u); write_empty(outputIndex, 8u); return; }
    atomicAdd(&diagnostics.tlasNodeTests, 1u);
    if (!tlas_bounds_hit(tlasNodeIndex, origin, direction, tMin, min(tMax, best.t))) { continue; }
    let tlasBase = tlasNodeIndex * 8u;
    let leftFirst = tlasNodes[tlasBase + 3u];
    let nodeMeta = tlasNodes[tlasBase + 7u];
    if ((nodeMeta & LEAF_BIT) == 0u) {
      if (stackSize + 2u > min(params.stackLimit, STACK_CAPACITY)) { atomicAdd(&diagnostics.stackOverflows, 1u); write_empty(outputIndex, 4u); return; }
      stack[stackSize] = nodeMeta & INDEX_MASK; stack[stackSize + 1u] = leftFirst; stackSize += 2u; continue;
    }
    let instanceEnd = leftFirst + (nodeMeta & INDEX_MASK);
    for (var instanceIndex = leftFirst; instanceIndex < instanceEnd; instanceIndex++) {
      if (instanceIndex >= params.instanceCount || instanceIndex * 36u + 35u >= arrayLength(&instances)) { atomicAdd(&diagnostics.invalidAccesses, 1u); write_empty(outputIndex, 8u); return; }
      let instanceBase = instanceIndex * 36u;
      let tableIndex = instances[instanceBase + 32u];
      if (tableIndex * 4u + 3u >= arrayLength(&blasTable)) { atomicAdd(&diagnostics.invalidAccesses, 1u); write_empty(outputIndex, 8u); return; }
      let blasRoot = blasTable[tableIndex * 4u];
      if (blasRoot == MISSING) { continue; }
      let localOrigin = transform_point(instanceIndex, origin, true);
      let localDirection = transform_vector(instanceIndex, direction, true);
      let blasStackBase = stackSize;
      if (stackSize + 1u > min(params.stackLimit, STACK_CAPACITY)) { atomicAdd(&diagnostics.stackOverflows, 1u); write_empty(outputIndex, 4u); return; }
      stack[stackSize] = blasRoot | LEAF_BIT; stackSize++;
      loop {
        if (stackSize == blasStackBase) { break; }
        stackSize--;
        let blasNodeIndex = stack[stackSize] & INDEX_MASK;
        if (blasNodeIndex * 8u + 7u >= arrayLength(&blasNodes)) { atomicAdd(&diagnostics.invalidAccesses, 1u); write_empty(outputIndex, 8u); return; }
        atomicAdd(&diagnostics.blasNodeTests, 1u);
        if (!blas_bounds_hit(blasNodeIndex, localOrigin, localDirection, tMin, min(tMax, best.t))) { continue; }
        let blasBase = blasNodeIndex * 8u;
        let primitiveFirst = blasNodes[blasBase + 3u];
        let blasMeta = blasNodes[blasBase + 7u];
        if ((blasMeta & LEAF_BIT) == 0u) {
          if (stackSize + 2u > min(params.stackLimit, STACK_CAPACITY)) { atomicAdd(&diagnostics.stackOverflows, 1u); write_empty(outputIndex, 4u); return; }
          stack[stackSize] = (blasMeta & INDEX_MASK) | LEAF_BIT; stack[stackSize + 1u] = primitiveFirst | LEAF_BIT; stackSize += 2u; continue;
        }
        let primitiveEnd = primitiveFirst + (blasMeta & INDEX_MASK);
        for (var primitiveIndex = primitiveFirst; primitiveIndex < primitiveEnd; primitiveIndex++) {
          if (primitiveIndex * 16u + 15u >= arrayLength(&primitives)) { atomicAdd(&diagnostics.invalidAccesses, 1u); write_empty(outputIndex, 8u); return; }
          atomicAdd(&diagnostics.primitiveTests, 1u);
          let kind = primitives[primitiveIndex * 16u + 12u];
          var candidate = empty_candidate();
          if (kind == 0u) { candidate = triangle_candidate(primitiveIndex, instanceIndex, origin, direction, tMin, tMax); }
          else if (kind == 1u) { candidate = sphere_candidate(primitiveIndex, instanceIndex, origin, direction, tMin, tMax); }
          if (candidate.hit == 0u) { continue; }
          let instanceIdentity = instances[instanceBase + 34u];
          let tieEpsilon = 1e-6 * max(max(1.0, abs(candidate.t)), abs(best.t));
          let preferred = candidate.t < best.t - tieEpsilon || (abs(candidate.t - best.t) <= tieEpsilon && (instanceIdentity < bestInstanceIdentity || (instanceIdentity == bestInstanceIdentity && candidate.primitiveIndex < best.primitiveIndex)));
          if (preferred) {
            best = candidate; bestInstanceIdentity = instanceIdentity;
            if (params.mode == 1u) { write_candidate(outputIndex, best, bestInstanceIdentity); atomicAdd(&diagnostics.hits, 1u); return; }
          }
        }
      }
    }
  }
  if (best.hit != 0u) { write_candidate(outputIndex, best, bestInstanceIdentity); atomicAdd(&diagnostics.hits, 1u); }
  else { atomicAdd(&diagnostics.misses, 1u); }
}
