import type { RuntimeAsset, RuntimeAssetSource, RuntimeLayoutDocument } from './runtime-types.js';

export type LayoutNetworkPolicy = { readonly mode: 'deny' } | { readonly mode: 'same-origin'; readonly baseUrl: string } | { readonly mode: 'allow-list'; readonly baseUrl: string; readonly origins: readonly string[] };
export interface LayoutAssetResolver { resolve(uri: string, signal: AbortSignal): Promise<Uint8Array | ArrayBuffer>; }
export interface LayoutAssetMaterialized { destroy(): void; }
export interface LayoutAssetMaterializer { materialize(asset: RuntimeAsset, bytes: Uint8Array, device: GPUDevice | undefined, signal: AbortSignal): Promise<LayoutAssetMaterialized>; }
export interface LayoutAssetHandle { readonly id: string; readonly generation: number; readonly bytes: Uint8Array; readonly materialized?: LayoutAssetMaterialized; release(): void; }
export interface LayoutAssetOwnerOptions { readonly resolver?: LayoutAssetResolver; readonly policy: LayoutNetworkPolicy; readonly materializer?: LayoutAssetMaterializer; readonly maxAssetBytes?: number; readonly maxTotalBytes?: number; readonly device?: GPUDevice; }
export class LayoutAssetError extends Error { readonly name = 'LayoutAssetError'; constructor(readonly code: 'E_LAYOUT_ASSET_REFERENCE' | 'E_LAYOUT_ASSET_NETWORK' | 'E_LAYOUT_ASSET_INTEGRITY' | 'E_LAYOUT_ASSET_LIMIT' | 'E_LAYOUT_ASSET_ABORTED' | 'E_LAYOUT_ASSET_DISPOSED', message: string) { super(message); } }
interface Entry { generation: number; refs: number; controller: AbortController; promise: Promise<Resolved>; resolved?: Resolved; }
interface Resolved { readonly bytes: Uint8Array; materialized?: LayoutAssetMaterialized; }

export class LayoutAssetOwner {
  private readonly assets: Map<string, RuntimeAsset>;
  private readonly entries = new Map<string, Entry>();
  private readonly cache = new Map<string, Uint8Array>();
  private readonly hosted = new Map<string, RuntimeAssetSource>();
  private readonly overrides = new Map<string, RuntimeAssetSource>();
  private disposed = false;
  private lost = false;
  private generation = 0;
  private device: GPUDevice | undefined;
  private totalBytes = 0;
  private readonly maxAssetBytes: number;
  private readonly maxTotalBytes: number;
  constructor(readonly document: RuntimeLayoutDocument, private readonly options: LayoutAssetOwnerOptions) { this.assets = new Map(document.assets.map(asset => [asset.id, asset])); this.device = options.device; this.maxAssetBytes = options.maxAssetBytes ?? 256 * 1024 * 1024; this.maxTotalBytes = options.maxTotalBytes ?? 1024 * 1024 * 1024; }

  setHostedReplacement(slot: string, source: RuntimeAssetSource): void { this.assertLive(); if (!slot) throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', 'Hosted slot must be non-empty.'); this.hosted.set(slot, source); for (const asset of this.assets.values()) if (asset.kind !== 'folder' && asset.source.kind === 'hosted' && asset.source.slot === slot) this.retire(asset.id); }
  replace(id: string, source: RuntimeAssetSource): void { this.assertLive(); if (!this.assets.has(id)) throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', `Unknown asset ${id}.`); this.retire(id); this.overrides.set(id, source); }
  async load(id: string): Promise<LayoutAssetHandle> { this.assertLive(); const asset = this.assets.get(id); if (!asset || asset.kind === 'folder') throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', `Asset ${id} is not loadable.`); let entry = this.entries.get(id); if (!entry) { const controller = new AbortController(), generation = this.generation; entry = { generation, refs: 0, controller, promise: this.resolve(asset, this.overrides.get(id) ?? asset.source, controller.signal, new Set([id])).then(async bytes => { if (controller.signal.aborted || this.disposed || this.generation !== generation) throw new LayoutAssetError('E_LAYOUT_ASSET_ABORTED', `Late asset ${id} result was retired.`); const resolved: Resolved = { bytes, ...(this.options.materializer && !this.lost ? { materialized: await this.options.materializer.materialize(asset, bytes, this.device, controller.signal) } : {}) }; if (controller.signal.aborted || this.disposed || this.generation !== generation) { resolved.materialized?.destroy(); throw new LayoutAssetError('E_LAYOUT_ASSET_ABORTED', `Late materialization for ${id} was retired.`); } entry!.resolved = resolved; return resolved; }) }; this.entries.set(id, entry); }
    entry.refs++; try { const resolved = await entry.promise; let released = false; return Object.freeze({ id, generation: entry.generation, bytes: resolved.bytes, ...(resolved.materialized === undefined ? {} : { materialized: resolved.materialized }), release: () => { if (released) return; released = true; this.release(id, entry!); } }); } catch (error) { entry.refs--; if (this.entries.get(id) === entry && entry.refs <= 0) this.entries.delete(id); throw error; }
  }

  notifyDeviceLost(): void { if (this.disposed || this.lost) return; this.lost = true; for (const entry of this.entries.values()) if (entry.resolved?.materialized) { entry.resolved.materialized.destroy(); delete entry.resolved.materialized; } }
  async recoverDevice(device: GPUDevice): Promise<void> { this.assertLive(); this.notifyDeviceLost(); this.device = device; if (!this.options.materializer) { this.lost = false; return; } const generation = ++this.generation, rebuilt: Array<{ entry: Entry; handle: LayoutAssetMaterialized }> = []; try { for (const [id, entry] of this.entries) { if (!entry.resolved || entry.refs <= 0) continue; const asset = this.assets.get(id)!; const handle = await this.options.materializer.materialize(asset, entry.resolved.bytes, device, entry.controller.signal); if (this.disposed || generation !== this.generation) { handle.destroy(); throw new LayoutAssetError('E_LAYOUT_ASSET_ABORTED', 'Device recovery was superseded.'); } rebuilt.push({ entry, handle }); } } catch (error) { for (const item of rebuilt) item.handle.destroy(); throw error; } for (const item of rebuilt) item.entry.resolved!.materialized = item.handle; this.lost = false; }
  dispose(): void { if (this.disposed) return; this.disposed = true; this.generation++; for (const id of [...this.entries.keys()]) this.retire(id); this.entries.clear(); this.cache.clear(); this.hosted.clear(); this.overrides.clear(); this.totalBytes = 0; }
  get stats(): Readonly<{ entries: number; references: number; cacheEntries: number; totalBytes: number; generation: number; lost: boolean; disposed: boolean }> { return Object.freeze({ entries: this.entries.size, references: [...this.entries.values()].reduce((sum, entry) => sum + entry.refs, 0), cacheEntries: this.cache.size, totalBytes: this.totalBytes, generation: this.generation, lost: this.lost, disposed: this.disposed }); }

  private async resolve(asset: RuntimeAsset, source: RuntimeAssetSource, signal: AbortSignal, stack: Set<string>): Promise<Uint8Array> { if (signal.aborted) throw new LayoutAssetError('E_LAYOUT_ASSET_ABORTED', `Asset ${asset.id} was aborted.`); if (source.kind === 'hosted') { const slotKey = `@slot:${source.slot}`; if (stack.has(slotKey)) throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', 'Hosted replacement cycle.'); stack.add(slotKey); const replacement = this.hosted.get(source.slot); if (replacement) return this.resolve(asset, replacement, signal, stack); if (source.fallbackAsset) { if (stack.has(source.fallbackAsset)) throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', 'Hosted fallback cycle.'); const fallback = this.assets.get(source.fallbackAsset); if (!fallback || fallback.kind === 'folder') throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', `Missing fallback ${source.fallbackAsset}.`); stack.add(fallback.id); return this.resolve(fallback, this.overrides.get(fallback.id) ?? fallback.source, signal, stack); } throw new LayoutAssetError('E_LAYOUT_ASSET_REFERENCE', `Hosted slot ${source.slot} has no replacement.`); }
    const effective = source, expected = effective.integrity; if (effective.kind === 'referenced') this.checkNetwork(effective.uri); const cached = this.cache.get(expected); if (cached) return cached;
    let bytes: Uint8Array; if (effective.kind === 'embedded') bytes = Uint8Array.from(effective.data); else { this.checkNetwork(effective.uri); if (!this.options.resolver) throw new LayoutAssetError('E_LAYOUT_ASSET_NETWORK', 'No resolver was supplied.'); try { const result = await this.options.resolver.resolve(effective.uri, signal); bytes = result instanceof Uint8Array ? new Uint8Array(result) : new Uint8Array(result.slice(0)); } catch (error) { if (signal.aborted) throw new LayoutAssetError('E_LAYOUT_ASSET_ABORTED', `Asset ${asset.id} was aborted.`); throw new LayoutAssetError('E_LAYOUT_ASSET_NETWORK', error instanceof Error ? error.message : String(error)); } }
    if (bytes.byteLength > this.maxAssetBytes || this.totalBytes + bytes.byteLength > this.maxTotalBytes) throw new LayoutAssetError('E_LAYOUT_ASSET_LIMIT', `Asset ${asset.id} exceeds byte budget.`); const digest = await sha256(bytes), actual = expected.length === 71 ? `sha256-${hex(digest)}` : `sha256-${base64(digest)}`; if (actual !== expected) throw new LayoutAssetError('E_LAYOUT_ASSET_INTEGRITY', `Asset ${asset.id} expected ${expected}, received ${actual}.`); if (signal.aborted) throw new LayoutAssetError('E_LAYOUT_ASSET_ABORTED', `Asset ${asset.id} was aborted.`); const stable = new Uint8Array(bytes); this.cache.set(expected, stable); this.totalBytes += stable.byteLength; return stable; }
  private checkNetwork(uri: string): void { if (this.options.policy.mode === 'deny') throw new LayoutAssetError('E_LAYOUT_ASSET_NETWORK', 'Network access is denied by host policy.'); let resolved: URL; try { resolved = new URL(uri, this.options.policy.baseUrl); } catch { throw new LayoutAssetError('E_LAYOUT_ASSET_NETWORK', `Invalid asset URL ${uri}.`); } const base = new URL(this.options.policy.baseUrl); if (this.options.policy.mode === 'same-origin' && resolved.origin !== base.origin) throw new LayoutAssetError('E_LAYOUT_ASSET_NETWORK', `Cross-origin asset ${resolved.origin} is denied.`); if (this.options.policy.mode === 'allow-list' && resolved.origin !== base.origin && !this.options.policy.origins.includes(resolved.origin)) throw new LayoutAssetError('E_LAYOUT_ASSET_NETWORK', `Origin ${resolved.origin} is not allowed.`); }
  private release(id: string, entry: Entry): void { if (this.entries.get(id) !== entry) return; entry.refs--; if (entry.refs <= 0) this.retire(id); }
  private retire(id: string): void { const entry = this.entries.get(id); if (!entry) return; entry.controller.abort(); entry.resolved?.materialized?.destroy(); this.entries.delete(id); }
  private assertLive(): void { if (this.disposed) throw new LayoutAssetError('E_LAYOUT_ASSET_DISPOSED', 'Asset owner is disposed.'); }
}

async function sha256(bytes: Uint8Array): Promise<Uint8Array> { return new Uint8Array(await crypto.subtle.digest('SHA-256', bytes as Uint8Array<ArrayBuffer>)); }
function base64(bytes: Uint8Array): string { const table = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/', output: string[] = []; for (let index = 0; index < bytes.length; index += 3) { const a = bytes[index]!, b = bytes[index + 1], c = bytes[index + 2], value = a << 16 | (b ?? 0) << 8 | (c ?? 0); output.push(table[value >>> 18 & 63]!, table[value >>> 12 & 63]!, b === undefined ? '=' : table[value >>> 6 & 63]!, c === undefined ? '=' : table[value & 63]!); } return output.join(''); }
function hex(bytes: Uint8Array): string { return [...bytes].map(value => value.toString(16).padStart(2, '0')).join(''); }
