import { TextEvaluator } from '../../text/parameterized/TextEvaluator.js';
import type { TextBlockPose } from '../../text/parameterized/runtime-types.js';
import { evaluateNSlice } from './NSlice.js';
import type { LayoutEvaluateRequest, LayoutEvaluation, LayoutInstancePose, LayoutNodePose, LayoutRect, LayoutRuntimeLimits, RuntimeArtboard, RuntimeLayoutDocument, RuntimeLength, RuntimeNode } from './runtime-types.js';

export class LayoutEvaluationError extends Error { readonly name = 'LayoutEvaluationError'; constructor(readonly code: 'E_LAYOUT_RUNTIME_FORMAT' | 'E_LAYOUT_RUNTIME_REFERENCE' | 'E_LAYOUT_RUNTIME_LIMIT' | 'E_LAYOUT_RUNTIME_ABORTED' | 'E_LAYOUT_RUNTIME_DISPOSED', message: string) { super(message); } }
const DEFAULT_LIMITS: LayoutRuntimeLimits = Object.freeze({ maxGlyphs: 1_000_000, maxLines: 250_000, maxLayoutPasses: 64, maxNestedDepth: 128, maxComponentInstances: 8192, maxListItems: 100_000, maxVirtualizedWindow: 4096, maxNslicePatches: 1_000_000 });
interface Size { readonly width: number; readonly height: number; }
interface WorkingNodePose extends Omit<LayoutNodePose, 'rect' | 'text' | 'nSlice'> { rect: LayoutRect; text?: TextBlockPose; nSlice?: LayoutNodePose['nSlice']; }

export class LayoutEvaluator {
  private readonly text: TextEvaluator;
  private readonly artboards: Map<string, RuntimeArtboard>;
  private readonly assets: Map<string, RuntimeLayoutDocument['assets'][number]>;
  private disposed = false;
  constructor(readonly document: RuntimeLayoutDocument, readonly limits: LayoutRuntimeLimits = DEFAULT_LIMITS) { if (document.format !== 'haiyue-responsive-layout-2d' || document.version !== 1 || document.extension !== 'org.haiyue.layout-2d@1') throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_FORMAT', 'Unsupported layout document.'); this.artboards = new Map(document.artboards.map(artboard => [artboard.id, artboard])); this.assets = new Map(document.assets.map(asset => [asset.id, asset])); this.text = new TextEvaluator(document, { maxGlyphs: limits.maxGlyphs, maxLines: limits.maxLines }); }
  evaluate(request: LayoutEvaluateRequest): LayoutEvaluation { if (this.disposed) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_DISPOSED', 'Layout evaluator is disposed.'); validateRequest(request); const context = new EvaluationContext(this, request); return context.run(); }
  dispose(): void { if (this.disposed) return; this.disposed = true; this.text.dispose(); }
  getText(): TextEvaluator { return this.text; }
  getArtboard(id: string): RuntimeArtboard | undefined { return this.artboards.get(id); }
  getAsset(id: string): RuntimeLayoutDocument['assets'][number] | undefined { return this.assets.get(id); }
}

class EvaluationContext {
  private readonly nodes: WorkingNodePose[] = [];
  private readonly nodeByKey = new Map<string, WorkingNodePose>();
  private readonly instances: LayoutInstancePose[] = [];
  private componentInstances = 0;
  private visibleListItems = 0;
  private nSlicePatches = 0;
  private readonly measureCache = new Map<string, Size>();
  constructor(private readonly owner: LayoutEvaluator, private readonly request: LayoutEvaluateRequest) {}
  run(): LayoutEvaluation { if (this.owner.limits.maxLayoutPasses < 2) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_LIMIT', 'Two deterministic layout passes are required.'); for (const instance of this.owner.document.instances) { this.abort(); const artboard = this.artboard(instance.artboard), rect = fitRect({ x: 0, y: 0, width: this.request.viewport[0], height: this.request.viewport[1] }, { width: artboard.width, height: artboard.height }, instance.fit ?? 'contain', instance.alignment ?? [0, 0]); this.layoutArtboard(instance.id, artboard, rect, 1, undefined, undefined, undefined); } return Object.freeze({ viewport: this.request.viewport, dpr: this.request.dpr, time: this.request.time, nodes: Object.freeze(this.nodes.map(node => Object.freeze(node) as LayoutNodePose)), instances: Object.freeze(this.instances), visibleListItems: this.visibleListItems, layoutPasses: 2 }); }

  private layoutArtboard(instanceId: string, artboard: RuntimeArtboard, rect: LayoutRect, depth: number, parentId: string | undefined, hostNode: string | undefined, item: unknown): void { this.abort(); if (depth > this.owner.limits.maxNestedDepth) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_LIMIT', 'Nested artboard depth exceeded.'); if (++this.componentInstances > this.owner.limits.maxComponentInstances) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_LIMIT', 'Component instance budget exceeded.'); const keyPrefix = instanceId, nodeMap = new Map(artboard.nodes.map(node => [node.id, node])), children = new Map<string, RuntimeNode[]>(); for (const node of artboard.nodes) if (node.parent) { const list = children.get(node.parent) ?? []; list.push(node); children.set(node.parent, list); } const inputs = this.request.componentInputs?.[hostNode ?? instanceId] ?? {}, events = this.request.componentEvents?.[hostNode ?? instanceId] ?? []; this.instances.push(Object.freeze({ id: instanceId, artboardId: artboard.id, ...(parentId === undefined ? {} : { parentId }), ...(hostNode === undefined ? {} : { hostNode }), rect, times: [this.request.time], mixWeight: 0, inputs, events })); const root = nodeMap.get(artboard.root); if (!root) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_REFERENCE', `Missing root ${artboard.root}.`); this.layoutNode(instanceId, artboard, root, rect, children, depth, true, item); }

  private layoutNode(instanceId: string, artboard: RuntimeArtboard, node: RuntimeNode, assigned: LayoutRect, children: ReadonlyMap<string, readonly RuntimeNode[]>, depth: number, forced: boolean, item: unknown): void { this.abort(); if (node.style.display === 'none') return; const intrinsic = this.measure(artboard, node, children, new Set()), rect = this.reflow(`${instanceId}/${node.id}`, forced ? assigned : sizeRect(assigned, node, intrinsic)), clip = node.visual?.clip || node.style.overflow === 'hidden' || node.style.overflow === 'scroll' ? rect : undefined, pose: WorkingNodePose = { key: `${instanceId}/${node.id}`, instanceId, artboardId: artboard.id, nodeId: node.id, kind: node.kind, rect, ...(clip === undefined ? {} : { clip }), opacity: node.visual?.opacity ?? 1, ...(node.visual?.background === undefined ? {} : { background: node.visual.background }), ...(node.visual?.borderColor === undefined ? {} : { borderColor: node.visual.borderColor }), borderWidth: node.visual?.borderWidth ?? [0, 0, 0, 0], cornerRadius: node.visual?.cornerRadius ?? [0, 0, 0, 0], ...(node.asset === undefined ? {} : { asset: node.asset }), ...(item === undefined ? {} : { item }) }; this.nodes.push(pose); this.nodeByKey.set(pose.key, pose);
    if (node.kind === 'text' && node.text) pose.text = translateText(this.owner.getText().evaluate(node.text, this.request), rect.x, rect.y);
    if (node.kind === 'n-slice' && node.nSlice) { const remaining = this.owner.limits.maxNslicePatches - this.nSlicePatches; try { pose.nSlice = evaluateNSlice(node.nSlice, rect, remaining); } catch { throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_LIMIT', 'N-slice patch budget exceeded.'); } this.nSlicePatches += pose.nSlice.length; }
    const childNodes = children.get(node.id) ?? []; if (childNodes.length > 0) this.layoutChildren(instanceId, artboard, node, rect, childNodes, children, depth, item);
    if (node.kind === 'component' && node.component) this.layoutComponent(instanceId, artboard, node, rect, depth, item);
    if (node.kind === 'list' && node.list) this.layoutList(instanceId, node, rect, depth);
    if (node.scroll?.scrollbar) this.applyScrollbar(instanceId, node, rect, intrinsic);
  }

  private layoutChildren(instanceId: string, artboard: RuntimeArtboard, parent: RuntimeNode, rect: LayoutRect, values: readonly RuntimeNode[], children: ReadonlyMap<string, readonly RuntimeNode[]>, depth: number, item: unknown): void { const padding = edge(parent.style.padding, rect), content: LayoutRect = { x: rect.x + padding[0], y: rect.y + padding[1], width: Math.max(0, rect.width - padding[0] - padding[2]), height: Math.max(0, rect.height - padding[1] - padding[3]) }, scroll = this.scrollOffset(`${instanceId}/${parent.id}`, parent, this.measure(artboard, parent, children, new Set()), rect); if (parent.style.display === 'grid') this.layoutGrid(instanceId, artboard, content, values, children, depth, item, scroll); else this.layoutFlex(instanceId, artboard, parent, content, values, children, depth, item, scroll); }

  private layoutFlex(instanceId: string, artboard: RuntimeArtboard, parent: RuntimeNode, content: LayoutRect, values: readonly RuntimeNode[], children: ReadonlyMap<string, readonly RuntimeNode[]>, depth: number, item: unknown, scroll: readonly [number, number]): void {
    const row = (parent.style.direction ?? 'row') === 'row', normal = values.filter(node => node.style.position !== 'absolute'), absolute = values.filter(node => node.style.position === 'absolute'), gapMain = resolveLength(parent.style.gap?.[row ? 0 : 1], row ? content.width : content.height, 0), gapCross = resolveLength(parent.style.gap?.[row ? 1 : 0], row ? content.height : content.width, 0), availableMain = row ? content.width : content.height, availableCross = row ? content.height : content.width;
    const measured = normal.map(node => this.measure(artboard, node, children, new Set())), sizes = normal.map((node, index) => nodeSize(node, content, measured[index]!)), margins = normal.map(node => edge(node.style.margin, content)), mainSizes = sizes.map(size => row ? size.width : size.height), crossSizes = sizes.map(size => row ? size.height : size.width), mainBefore = margins.map(value => value[row ? 0 : 1]), mainAfter = margins.map(value => value[row ? 2 : 3]), crossBefore = margins.map(value => value[row ? 1 : 0]), crossAfter = margins.map(value => value[row ? 3 : 2]), fillWeights = normal.map(node => { const length = row ? node.style.width : node.style.height; return length?.unit === 'fraction' ? length.value : length?.unit === 'fill' ? 1 : 0; }), totalWeight = fillWeights.reduce((sum, value) => sum + value, 0), fixed = mainSizes.reduce((sum, size, index) => sum + mainBefore[index]! + mainAfter[index]! + (fillWeights[index]! > 0 ? 0 : size), 0) + Math.max(0, normal.length - 1) * gapMain, remaining = Math.max(0, availableMain - fixed);
    if (totalWeight > 0) fillWeights.forEach((weight, index) => { if (weight > 0) mainSizes[index] = clampDimension(normal[index]!, row ? 'width' : 'height', availableMain, remaining * weight / totalWeight); });
    const ordered = parent.style.writingDirection === 'rtl' && row ? normal.map((_, index) => normal.length - 1 - index) : normal.map((_, index) => index), totalMain = mainSizes.reduce((sum, value, index) => sum + value + mainBefore[index]! + mainAfter[index]!, 0) + Math.max(0, normal.length - 1) * gapMain, justify = justifyOffsets(parent.style.justify ?? 'start', availableMain, totalMain, normal.length); let cursor = justify.start, lineCross = 0, crossCursor = 0;
    for (const index of ordered) {
      const node = normal[index]!, main = mainSizes[index]!, align = node.style.justifySelf && node.style.justifySelf !== 'auto' ? node.style.justifySelf : parent.style.align ?? 'start', before = mainBefore[index]!, after = mainAfter[index]!, beforeCross = crossBefore[index]!, afterCross = crossAfter[index]!; let cross = align === 'stretch' ? Math.max(0, availableCross - beforeCross - afterCross) : crossSizes[index]!;
      const occupiedMain = before + main + after; if (parent.style.wrap && cursor > 0 && cursor + occupiedMain > availableMain) { cursor = 0; crossCursor += lineCross + gapCross; lineCross = 0; }
      const crossAvailable = availableCross - crossCursor - beforeCross - afterCross, crossOffset = align === 'center' ? Math.max(0, crossAvailable - cross) * 0.5 : align === 'end' ? Math.max(0, crossAvailable - cross) : 0, relative = relativeOffset(node, content), childRect: LayoutRect = row ? { x: content.x + cursor + before + relative[0] - scroll[0], y: content.y + crossCursor + beforeCross + crossOffset + relative[1] - scroll[1], width: main, height: cross } : { x: content.x + crossCursor + beforeCross + crossOffset + relative[0] - scroll[0], y: content.y + cursor + before + relative[1] - scroll[1], width: cross, height: main };
      this.layoutNode(instanceId, artboard, node, childRect, children, depth, true, item); cursor += occupiedMain + gapMain + justify.between; lineCross = Math.max(lineCross, beforeCross + cross + afterCross);
    }
    for (const node of absolute) this.layoutNode(instanceId, artboard, node, absoluteRect(content, node, this.measure(artboard, node, children, new Set()), scroll), children, depth, true, item); }

  private layoutGrid(instanceId: string, artboard: RuntimeArtboard, content: LayoutRect, values: readonly RuntimeNode[], children: ReadonlyMap<string, readonly RuntimeNode[]>, depth: number, item: unknown, scroll: readonly [number, number]): void { const columns = tracks(artboard, values, children, content.width, values[0]?.parent ? this.node(values[0]!.parent, artboard)?.style.gridColumns : undefined, true, this), rows = tracks(artboard, values, children, content.height, values[0]?.parent ? this.node(values[0]!.parent, artboard)?.style.gridRows : undefined, false, this); const columnOffsets = offsets(columns), rowOffsets = offsets(rows); for (const [index, node] of values.entries()) { const placement = node.style.gridPlacement ?? { column: index % columns.length, row: Math.floor(index / columns.length) }, column = Math.min(columns.length - 1, placement.column), row = Math.min(rows.length - 1, placement.row), columnSpan = Math.min(columns.length - column, placement.columnSpan ?? 1), rowSpan = Math.min(rows.length - row, placement.rowSpan ?? 1), rect: LayoutRect = { x: content.x + columnOffsets[column]! - scroll[0], y: content.y + rowOffsets[row]! - scroll[1], width: columns.slice(column, column + columnSpan).reduce((sum, value) => sum + value, 0), height: rows.slice(row, row + rowSpan).reduce((sum, value) => sum + value, 0) }; this.layoutNode(instanceId, artboard, node, rect, children, depth, true, item); } }

  private layoutComponent(instanceId: string, _artboard: RuntimeArtboard, node: RuntimeNode, rect: LayoutRect, depth: number, item: unknown): void { const component = node.component!, key = `${instanceId}/${node.id}`, replacement = this.request.componentReplacements?.[key] ?? this.request.componentReplacements?.[node.id] ?? component.artboard, nested = this.artboard(replacement), nestedRect = component.sizing === 'node' || component.sizing === 'layout' ? rect : fitRect(rect, { width: nested.width, height: nested.height }, component.fit ?? 'contain', component.alignment ?? [0, 0]), inputs = this.request.componentInputs?.[key] ?? {}, events = (this.request.componentEvents?.[key] ?? []).filter(event => component.exposedEvents?.includes(event.name) ?? true), timing = componentTime(component, key, this.request, inputs), nestedId = `${key}@${replacement}`; this.layoutArtboard(nestedId, nested, nestedRect, depth + 1, instanceId, key, item); const pose = this.instances.find(candidate => candidate.id === nestedId); if (pose) { const index = this.instances.indexOf(pose); this.instances[index] = Object.freeze({ ...pose, times: timing.times, mixWeight: timing.mixWeight, inputs: filterInputs(inputs, component.exposedInputs), events }); } }

  private layoutList(instanceId: string, node: RuntimeNode, rect: LayoutRect, depth: number): void { const list = node.list!, values = this.request.lists?.[list.dataPort] ?? []; if (values.length > this.owner.limits.maxListItems) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_LIMIT', 'List item budget exceeded.'); const stride = list.itemExtent + (list.gap ?? 0), key = `${instanceId}/${node.id}`, input = this.request.scroll?.[key] ?? this.request.scroll?.[list.dataPort], raw = input?.offset?.[list.direction === 'row' ? 0 : 1] ?? 0, offset = list.carousel && input?.settled ? Math.round(raw / stride) * stride : raw, extent = list.direction === 'row' ? rect.width : rect.height, buffer = Math.min(this.owner.limits.maxVirtualizedWindow, list.buffer ?? 1), start = list.virtualize ? Math.max(0, Math.floor(offset / stride) - buffer) : 0, end = list.virtualize ? Math.min(values.length, Math.ceil((offset + extent) / stride) + buffer) : values.length; if (end - start > this.owner.limits.maxVirtualizedWindow && list.virtualize) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_LIMIT', 'Virtualized window budget exceeded.'); const artboard = this.artboard(list.templateArtboard); for (let index = start; index < end; index++) { const value = values[index], identity = itemIdentity(value, index), itemRect: LayoutRect = list.direction === 'row' ? { x: rect.x + index * stride - offset, y: rect.y, width: list.itemExtent, height: rect.height } : { x: rect.x, y: rect.y + index * stride - offset, width: rect.width, height: list.itemExtent }; this.visibleListItems++; this.layoutArtboard(`${key}[${identity}]`, artboard, itemRect, depth + 1, instanceId, key, value); } }

  private measure(artboard: RuntimeArtboard, node: RuntimeNode, children: ReadonlyMap<string, readonly RuntimeNode[]>, visiting: Set<string>): Size { const cacheKey = `${artboard.id}/${node.id}`; const cached = this.measureCache.get(cacheKey); if (cached) return cached; if (visiting.has(cacheKey)) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_FORMAT', `Intrinsic measurement cycle ${cacheKey}.`); visiting.add(cacheKey); let size: Size = node.intrinsicSize ? { width: node.intrinsicSize[0], height: node.intrinsicSize[1] } : { width: 0, height: 0 }; if (node.kind === 'text' && node.text) { const text = this.owner.getText().evaluate(node.text, this.request); size = { width: text.contentWidth, height: text.contentHeight }; } else if (node.kind === 'image' && node.asset) { const asset = this.owner.getAsset(node.asset); if (asset?.kind === 'image') size = { width: asset.width, height: asset.height }; } else if (node.kind === 'component' && node.component) { const nested = this.artboard(node.component.artboard); size = { width: nested.width, height: nested.height }; } else if (node.kind === 'list' && node.list) { const count = this.request.lists?.[node.list.dataPort]?.length ?? 0, extent = count * node.list.itemExtent + Math.max(0, count - 1) * (node.list.gap ?? 0); size = node.list.direction === 'row' ? { width: extent, height: node.intrinsicSize?.[1] ?? 0 } : { width: node.intrinsicSize?.[0] ?? 0, height: extent }; } else if (node.kind === 'n-slice' && node.nSlice) size = { width: node.nSlice.sourceSize[0], height: node.nSlice.sourceSize[1] };
    const childValues = children.get(node.id) ?? []; if (childValues.length > 0) { const measured = childValues.filter(child => child.style.position !== 'absolute').map(child => this.measure(artboard, child, children, visiting)), row = (node.style.direction ?? 'row') === 'row', gap = resolveLength(node.style.gap?.[row ? 0 : 1], row ? artboard.width : artboard.height, 0), padding = edge(node.style.padding, { x: 0, y: 0, width: artboard.width, height: artboard.height }); size = { width: row ? measured.reduce((sum, item) => sum + item.width, 0) + Math.max(0, measured.length - 1) * gap + padding[0] + padding[2] : Math.max(0, ...measured.map(item => item.width)) + padding[0] + padding[2], height: row ? Math.max(0, ...measured.map(item => item.height)) + padding[1] + padding[3] : measured.reduce((sum, item) => sum + item.height, 0) + Math.max(0, measured.length - 1) * gap + padding[1] + padding[3] }; }
    visiting.delete(cacheKey); this.measureCache.set(cacheKey, size); return size; }

  private nodeDimension(node: RuntimeNode, axis: 'width' | 'height', parent: number, intrinsic: number): number { let value = resolveLength(node.style[axis], parent, intrinsic), min = resolveLength(node.style[axis === 'width' ? 'minWidth' : 'minHeight'], parent, 0), maxLength = node.style[axis === 'width' ? 'maxWidth' : 'maxHeight'], max = maxLength === undefined ? Infinity : resolveLength(maxLength, parent, Infinity); value = Math.max(min, Math.min(max, value)); return value; }
  private scrollOffset(key: string, node: RuntimeNode, intrinsic: Size, rect: LayoutRect): readonly [number, number] { if (!node.scroll) return [0, 0]; const input = this.request.scroll?.[key] ?? this.request.scroll?.[node.id], base = input?.offset ?? [0, 0], velocity = input?.active === false ? [0, 0] as const : input?.velocity ?? [0, 0], friction = node.scroll.friction ?? 0, decayFactor = friction > 0 ? (1 - Math.exp(-friction * Math.max(0, this.request.time))) / friction : Math.max(0, this.request.time), maxX = Math.max(0, intrinsic.width - rect.width), maxY = Math.max(0, intrinsic.height - rect.height); let x = base[0] + velocity[0] * decayFactor, y = base[1] + velocity[1] * decayFactor; if (node.scroll.snap && input?.settled) { x = Math.round(x / node.scroll.snap) * node.scroll.snap; y = Math.round(y / node.scroll.snap) * node.scroll.snap; } if (node.scroll.mode !== 'infinite') { if (node.scroll.mode === 'elastic') { x = elastic(x, 0, maxX, node.scroll.elasticity ?? 0.25); y = elastic(y, 0, maxY, node.scroll.elasticity ?? 0.25); } else { x = clamp(x, 0, maxX); y = clamp(y, 0, maxY); } } if (node.scroll.axis === 'x') y = 0; if (node.scroll.axis === 'y') x = 0; return [x, y]; }
  private applyScrollbar(instanceId: string, node: RuntimeNode, rect: LayoutRect, intrinsic: Size): void {
    const definition = node.scroll!.scrollbar!, target = this.nodeByKey.get(`${instanceId}/${definition.node}`); if (!target) return;
    const artboard = this.artboard(target.artboardId), childIds = new Set(artboard.nodes.filter(candidate => candidate.parent === node.id && candidate.id !== definition.node).map(candidate => candidate.id)), childPoses = this.nodes.filter(candidate => candidate.instanceId === instanceId && candidate.artboardId === target.artboardId && childIds.has(candidate.nodeId));
    const measuredWidth = Math.max(intrinsic.width, ...childPoses.map(candidate => candidate.rect.x + candidate.rect.width - rect.x)), measuredHeight = Math.max(intrinsic.height, ...childPoses.map(candidate => candidate.rect.y + candidate.rect.height - rect.y));
    const horizontal = node.scroll!.axis !== 'y', viewport = horizontal ? rect.width : rect.height, content = horizontal ? measuredWidth : measuredHeight, ratio = content > 0 ? Math.min(1, viewport / content) : 1, input = this.request.scroll?.[`${instanceId}/${node.id}`] ?? this.request.scroll?.[node.id], offset = input?.offset?.[horizontal ? 0 : 1] ?? 0, maximum = Math.max(0, content - viewport), position = maximum > 0 ? clamp(offset / maximum, 0, 1) * viewport * (1 - ratio) : 0;
    target.rect = horizontal ? { ...target.rect, x: rect.x + position, ...(definition.autoSize ? { width: viewport * ratio } : {}) } : { ...target.rect, y: rect.y + position, ...(definition.autoSize ? { height: viewport * ratio } : {}) };
  }
  private reflow(key: string, current: LayoutRect): LayoutRect { const prior = this.request.priorRects?.[key]; if (!prior) return current; const progress = clamp(this.request.reflowProgress ?? 1, 0, 1), nodeId = key.slice(key.lastIndexOf('/') + 1), node = this.owner.document.artboards.flatMap(artboard => artboard.nodes).find(candidate => candidate.id === nodeId), amount = node?.style.reflow ? cubicBezier(node.style.reflow.easing, progress) : progress; return { x: mix(prior.x, current.x, amount), y: mix(prior.y, current.y, amount), width: mix(prior.width, current.width, amount), height: mix(prior.height, current.height, amount) }; }
  private artboard(id: string): RuntimeArtboard { const artboard = this.owner.getArtboard(id); if (!artboard) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_REFERENCE', `Unknown artboard ${id}.`); return artboard; }
  private node(id: string, artboard: RuntimeArtboard): RuntimeNode | undefined { return artboard.nodes.find(node => node.id === id); }
  private abort(): void { if (this.request.signal?.aborted) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_ABORTED', 'Layout evaluation was aborted.'); }
}

function validateRequest(request: LayoutEvaluateRequest): void { if (request.viewport.length !== 2 || !request.viewport.every(value => Number.isFinite(value) && value >= 0) || !Number.isFinite(request.dpr) || request.dpr <= 0 || !Number.isFinite(request.time)) throw new LayoutEvaluationError('E_LAYOUT_RUNTIME_FORMAT', 'Viewport, DPR, and time must be finite.'); }
function sizeRect(parent: LayoutRect, node: RuntimeNode, intrinsic: Size): LayoutRect { const size = nodeSize(node, parent, intrinsic); return { x: parent.x, y: parent.y, width: size.width, height: size.height }; }
function nodeSize(node: RuntimeNode, parent: LayoutRect, intrinsic: Size): Size { let width = clampDimension(node, 'width', parent.width, resolveLength(node.style.width, parent.width, intrinsic.width)), height = clampDimension(node, 'height', parent.height, resolveLength(node.style.height, parent.height, intrinsic.height)); if (node.style.aspectRatio && node.style.aspectRatio > 0) { if (node.style.width !== undefined && node.style.height === undefined) height = clampDimension(node, 'height', parent.height, width / node.style.aspectRatio); else if (node.style.height !== undefined && node.style.width === undefined) width = clampDimension(node, 'width', parent.width, height * node.style.aspectRatio); } return { width, height }; }
function clampDimension(node: RuntimeNode, axis: 'width' | 'height', parent: number, value: number): number { const min = resolveLength(node.style[axis === 'width' ? 'minWidth' : 'minHeight'], parent, 0), maxLength = node.style[axis === 'width' ? 'maxWidth' : 'maxHeight'], max = maxLength === undefined ? Infinity : resolveLength(maxLength, parent, Infinity); return Math.max(min, Math.min(max, value)); }
function relativeOffset(node: RuntimeNode, parent: LayoutRect): readonly [number, number] { if (node.style.position === 'absolute' || !node.style.inset) return [0, 0]; const inset = edge(node.style.inset, parent), x = inset[0] !== 0 ? inset[0] : -inset[2], y = inset[1] !== 0 ? inset[1] : -inset[3]; return [x, y]; }
function resolveLength(length: RuntimeLength | undefined, parent: number, intrinsic: number): number { if (!length) return intrinsic; if (length.unit === 'point') return length.value; if (length.unit === 'percent') return parent * length.value / 100; if (length.unit === 'fraction' || length.unit === 'fill') return intrinsic; return intrinsic; }
function edge(value: readonly RuntimeLength[] | undefined, rect: LayoutRect): readonly [number, number, number, number] { if (!value) return [0, 0, 0, 0]; return [resolveLength(value[0], rect.width, 0), resolveLength(value[1], rect.height, 0), resolveLength(value[2], rect.width, 0), resolveLength(value[3], rect.height, 0)]; }
function absoluteRect(content: LayoutRect, node: RuntimeNode, intrinsic: Size, scroll: readonly [number, number]): LayoutRect { const inset = edge(node.style.inset, content), base = nodeSize(node, content, intrinsic), width = node.style.width ? base.width : clampDimension(node, 'width', content.width, Math.max(0, content.width - inset[0] - inset[2])), height = node.style.height ? base.height : clampDimension(node, 'height', content.height, Math.max(0, content.height - inset[1] - inset[3])); return { x: content.x + inset[0] - scroll[0], y: content.y + inset[1] - scroll[1], width, height }; }
function justifyOffsets(mode: NonNullable<RuntimeNode['style']['justify']>, available: number, used: number, count: number): { start: number; between: number } { const remaining = Math.max(0, available - used); if (mode === 'center') return { start: remaining / 2, between: 0 }; if (mode === 'end') return { start: remaining, between: 0 }; if (mode === 'space-between') return { start: 0, between: count > 1 ? remaining / (count - 1) : 0 }; if (mode === 'space-around') { const between = count > 0 ? remaining / count : 0; return { start: between / 2, between }; } if (mode === 'space-evenly') { const between = remaining / (count + 1); return { start: between, between }; } return { start: 0, between: 0 }; }
function tracks(artboard: RuntimeArtboard, nodes: readonly RuntimeNode[], children: ReadonlyMap<string, readonly RuntimeNode[]>, available: number, definitions: RuntimeNode['style']['gridColumns'] | undefined, horizontal: boolean, context: EvaluationContext): number[] { const tracks = definitions && definitions.length > 0 ? definitions : [{ min: { unit: 'fraction' as const, value: 1 } }], result = tracks.map(track => resolveLength(track.min, available, 0)), weights = tracks.map(track => track.min.unit === 'fraction' ? track.min.value : track.min.unit === 'fill' ? 1 : 0), fixed = result.reduce((sum, value, index) => sum + (weights[index]! > 0 ? 0 : value), 0), total = weights.reduce((sum, value) => sum + value, 0), remaining = Math.max(0, available - fixed); if (total > 0) weights.forEach((weight, index) => { if (weight > 0) result[index] = remaining * weight / total; }); void artboard; void nodes; void children; void horizontal; void context; return result; }
function offsets(values: readonly number[]): number[] { const result: number[] = []; let current = 0; for (const value of values) { result.push(current); current += value; } return result; }
function fitRect(target: LayoutRect, source: Size, fit: NonNullable<RuntimeRootFit>, alignment: readonly [number, number]): LayoutRect { if (fit === 'fill') return target; if (source.width <= 0 || source.height <= 0) return { x: target.x, y: target.y, width: 0, height: 0 }; const scale = fit === 'none' ? 1 : fit === 'cover' ? Math.max(target.width / source.width, target.height / source.height) : fit === 'scale-down' ? Math.min(1, Math.min(target.width / source.width, target.height / source.height)) : Math.min(target.width / source.width, target.height / source.height), width = source.width * scale, height = source.height * scale; return { x: target.x + (target.width - width) * (alignment[0] + 1) / 2, y: target.y + (target.height - height) * (alignment[1] + 1) / 2, width, height }; }
type RuntimeRootFit = RuntimeLayoutDocument['instances'][number]['fit'];
function translateText(pose: TextBlockPose, x: number, y: number): TextBlockPose { return Object.freeze({ ...pose, glyphs: Object.freeze(pose.glyphs.map(glyph => Object.freeze({ ...glyph, x: glyph.x + x, y: glyph.y + y }))), lines: Object.freeze(pose.lines.map(line => Object.freeze({ ...line, x: line.x + x, y: line.y + y }))), controls: Object.freeze(pose.controls.map(control => Object.freeze({ ...control, x: control.x + x, y: control.y + y }))) }); }
function componentTime(component: NonNullable<RuntimeNode['component']>, key: string, request: LayoutEvaluateRequest, inputs: Readonly<Record<string, unknown>>): { times: readonly number[]; mixWeight: number } { const playback = component.playback ?? { mode: 'simple' as const }, speed = playback.speed ?? 1; let base = playback.stateful ? request.componentStateTimes?.[key] ?? request.time * speed : request.time * speed; if (playback.paused) base = request.componentStateTimes?.[key] ?? 0; if (playback.quantize) base = Math.floor(base / playback.quantize) * playback.quantize; if (playback.mode === 'remap') return { times: [numberInput(inputs[playback.remapPort!])], mixWeight: 0 }; if (playback.mode === 'mix') { const weight = clamp(numberInput(inputs[playback.mixPort!]), 0, 1); return { times: [base, numberInput(inputs[playback.remapPort ?? playback.mixPort!])], mixWeight: weight }; } return { times: [base], mixWeight: 0 }; }
function filterInputs(inputs: Readonly<Record<string, unknown>>, allowed: readonly string[] | undefined): Readonly<Record<string, unknown>> { if (!allowed) return Object.freeze({ ...inputs }); return Object.freeze(Object.fromEntries(Object.entries(inputs).filter(([key]) => allowed.includes(key)))); }
function numberInput(value: unknown): number { if (typeof value !== 'number' || !Number.isFinite(value)) return 0; return value; }
function itemIdentity(value: unknown, index: number): string { if (value && typeof value === 'object' && 'id' in value && typeof (value as { id?: unknown }).id === 'string') return (value as { id: string }).id; return String(index); }
function elastic(value: number, minimum: number, maximum: number, factor: number): number { return value < minimum ? minimum + (value - minimum) * factor : value > maximum ? maximum + (value - maximum) * factor : value; }
function cubicBezier(easing: readonly [number, number, number, number], x: number): number { let low = 0, high = 1, t = x; for (let index = 0; index < 16; index++) { t = (low + high) / 2; const estimate = cubic(0, easing[0], easing[2], 1, t); if (estimate < x) low = t; else high = t; } return cubic(0, easing[1], easing[3], 1, t); }
function cubic(a: number, b: number, c: number, d: number, t: number): number { const u = 1 - t; return u * u * u * a + 3 * u * u * t * b + 3 * u * t * t * c + t * t * t * d; }
function mix(a: number, b: number, t: number): number { return a + (b - a) * t; }
function clamp(value: number, min: number, max: number): number { return Math.max(min, Math.min(max, value)); }
