import type { LayoutEvaluation, LayoutRect } from './runtime-types.js';
import type { RuntimeColor, RuntimePaintSource } from '../../text/parameterized/runtime-types.js';

export interface LayoutGpuStats { readonly bufferCount: number; readonly allocatedBytes: number; readonly vertexCount: number; readonly generation: number; readonly lost: boolean; readonly disposed: boolean; }

export class LayoutGpuRenderer {
  private device: GPUDevice;
  private pipeline: GPURenderPipeline;
  private buffer: GPUBuffer | undefined;
  private source = new Float32Array();
  private vertexCount = 0;
  private generation = 0;
  private lost = false;
  private disposed = false;
  constructor(device: GPUDevice, readonly format: GPUTextureFormat = 'rgba8unorm', private readonly maxGpuBytes = 512 * 1024 * 1024) { this.device = device; this.validateDevice(device); this.pipeline = this.createPipeline(device); this.watchLoss(device, 0); }

  upload(evaluation: LayoutEvaluation): void {
    this.assertLive(); const values: number[] = [], maximumBytes = Math.min(this.maxGpuBytes, this.device.limits.maxBufferSize);
    for (const node of evaluation.nodes) {
      if (node.background) roundedQuad(values, intersect(node.rect, node.clip), node.cornerRadius, alpha(node.background, node.opacity));
      if (node.borderColor) { const [left, top, right, bottom] = node.borderWidth, color = alpha(node.borderColor, node.opacity); quad(values, intersect({ x: node.rect.x, y: node.rect.y, width: left, height: node.rect.height }, node.clip), color); quad(values, intersect({ x: node.rect.x, y: node.rect.y, width: node.rect.width, height: top }, node.clip), color); quad(values, intersect({ x: node.rect.x + node.rect.width - right, y: node.rect.y, width: right, height: node.rect.height }, node.clip), color); quad(values, intersect({ x: node.rect.x, y: node.rect.y + node.rect.height - bottom, width: node.rect.width, height: bottom }, node.clip), color); }
      for (const glyph of node.text?.glyphs ?? []) {
        const glyphRect = { x: glyph.x, y: glyph.y, width: glyph.width, height: glyph.height }, transform = { rotation: glyph.rotation, scaleX: glyph.scaleX, scaleY: glyph.scaleY };
        for (const stroke of glyph.strokes) { const width = stroke.width, opacity = glyph.opacity * node.opacity * (stroke.opacity ?? 1); paintQuad(values, { x: glyph.x - width, y: glyph.y - width, width: glyph.width + width * 2, height: width }, stroke.source, opacity, node.clip, transform, glyphRect); paintQuad(values, { x: glyph.x - width, y: glyph.y + glyph.height, width: glyph.width + width * 2, height: width }, stroke.source, opacity, node.clip, transform, glyphRect); paintQuad(values, { x: glyph.x - width, y: glyph.y, width, height: glyph.height }, stroke.source, opacity, node.clip, transform, glyphRect); paintQuad(values, { x: glyph.x + glyph.width, y: glyph.y, width, height: glyph.height }, stroke.source, opacity, node.clip, transform, glyphRect); }
        for (const fill of glyph.fills) paintQuad(values, glyphRect, fill.source, glyph.opacity * node.opacity * (fill.opacity ?? 1), node.clip, transform, glyphRect);
        ensureBudget(values, maximumBytes);
      }
      for (const control of node.text?.controls ?? []) quad(values, intersect(control, node.clip), alpha(control.kind === 'cursor' ? [1, 1, 1, 1] : [0.2, 0.4, 1, 0.35], node.opacity));
      for (const patch of node.nSlice ?? []) { quad(values, intersect(patch, node.clip), alpha(hashColor(node.nodeId), node.opacity)); ensureBudget(values, maximumBytes); }
      ensureBudget(values, maximumBytes);
    }
    for (let index = 0; index < values.length; index += 6) { values[index] = evaluation.viewport[0] > 0 ? values[index]! / evaluation.viewport[0] * 2 - 1 : -1; values[index + 1] = evaluation.viewport[1] > 0 ? 1 - values[index + 1]! / evaluation.viewport[1] * 2 : 1; }
    const source = Float32Array.from(values); if (source.byteLength > this.maxGpuBytes || source.byteLength > this.device.limits.maxBufferSize) throw new Error('E_LAYOUT_GPU_BUDGET'); const next = source.byteLength > 0 ? this.device.createBuffer({ label: 'Layout2D.vertices', size: align4(source.byteLength), usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST }) : undefined; if (next) this.device.queue.writeBuffer(next, 0, source); this.buffer?.destroy(); this.buffer = next; this.source = source; this.vertexCount = source.length / 6;
  }
  render(pass: GPURenderPassEncoder): void { this.assertLive(); if (!this.buffer || this.vertexCount === 0) return; pass.setPipeline(this.pipeline); pass.setVertexBuffer(0, this.buffer); pass.draw(this.vertexCount); }
  notifyDeviceLost(): void { if (this.disposed || this.lost) return; this.lost = true; this.buffer?.destroy(); this.buffer = undefined; }
  recoverDevice(device: GPUDevice, generation = this.generation + 1): void { if (this.disposed) throw new Error('E_LAYOUT_GPU_DISPOSED'); this.notifyDeviceLost(); this.validateDevice(device); this.device = device; this.pipeline = this.createPipeline(device); const next = this.source.byteLength > 0 ? device.createBuffer({ label: 'Layout2D.vertices', size: align4(this.source.byteLength), usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST }) : undefined; if (next) device.queue.writeBuffer(next, 0, this.source); this.buffer = next; this.generation = generation; this.lost = false; this.watchLoss(device, generation); }
  dispose(): void { if (this.disposed) return; this.disposed = true; this.buffer?.destroy(); this.buffer = undefined; this.source = new Float32Array(); this.vertexCount = 0; }
  get stats(): LayoutGpuStats { return Object.freeze({ bufferCount: this.buffer ? 1 : 0, allocatedBytes: this.buffer?.size ?? 0, vertexCount: this.vertexCount, generation: this.generation, lost: this.lost, disposed: this.disposed }); }
  private validateDevice(device: GPUDevice): void { if (device.limits.maxBufferSize < 24 || device.limits.maxVertexBufferArrayStride < 24) throw new Error('E_LAYOUT_GPU_UNSUPPORTED_LIMITS'); }
  private createPipeline(device: GPUDevice): GPURenderPipeline { return device.createRenderPipeline({ label: 'Layout2D.pipeline', layout: 'auto', vertex: { module: device.createShaderModule({ label: 'Layout2D.shader', code: LAYOUT_GPU_WGSL }), entryPoint: 'vs', buffers: [{ arrayStride: 24, attributes: [{ shaderLocation: 0, format: 'float32x2', offset: 0 }, { shaderLocation: 1, format: 'float32x4', offset: 8 }] }] }, fragment: { module: device.createShaderModule({ label: 'Layout2D.shader', code: LAYOUT_GPU_WGSL }), entryPoint: 'fs', targets: [{ format: this.format, blend: { color: { operation: 'add', srcFactor: 'src-alpha', dstFactor: 'one-minus-src-alpha' }, alpha: { operation: 'add', srcFactor: 'one', dstFactor: 'one-minus-src-alpha' } } }] }, primitive: { topology: 'triangle-list' } }); }
  private watchLoss(device: GPUDevice, generation: number): void { void device.lost.then(() => { if (!this.disposed && this.device === device && this.generation === generation) this.notifyDeviceLost(); }); }
  private assertLive(): void { if (this.disposed) throw new Error('E_LAYOUT_GPU_DISPOSED'); if (this.lost) throw new Error('E_LAYOUT_GPU_DEVICE_LOST'); }
}

function quad(target: number[], rect: LayoutRect | undefined, color: RuntimeColor): void { if (!rect || rect.width <= 0 || rect.height <= 0) return; coloredQuad(target, [rect.x, rect.y], [rect.x + rect.width, rect.y], [rect.x, rect.y + rect.height], [rect.x + rect.width, rect.y + rect.height], color, color, color, color); }
function roundedQuad(target: number[], rect: LayoutRect | undefined, radii: readonly [number, number, number, number], color: RuntimeColor): void { if (!rect || rect.width <= 0 || rect.height <= 0) return; const maximum = Math.min(rect.width, rect.height) * 0.5, values = radii.map(radius => clamp(radius, 0, maximum)); if (values.every(radius => radius === 0)) { quad(target, rect, color); return; } const centers: readonly [number, number][] = [[rect.x + values[0]!, rect.y + values[0]!], [rect.x + rect.width - values[1]!, rect.y + values[1]!], [rect.x + rect.width - values[2]!, rect.y + rect.height - values[2]!], [rect.x + values[3]!, rect.y + rect.height - values[3]!]], starts = [Math.PI, Math.PI * 1.5, 0, Math.PI * 0.5], points: Array<readonly [number, number]> = []; for (let corner = 0; corner < 4; corner++) for (let step = 0; step <= 4; step++) { const angle = starts[corner]! + Math.PI * 0.5 * step / 4, radius = values[corner]!; points.push([centers[corner]![0] + Math.cos(angle) * radius, centers[corner]![1] + Math.sin(angle) * radius]); } const center: readonly [number, number] = [rect.x + rect.width * 0.5, rect.y + rect.height * 0.5]; for (let index = 0; index < points.length; index++) { const a = points[index]!, b = points[(index + 1) % points.length]!; vertex(target, center[0], center[1], color); vertex(target, a[0], a[1], color); vertex(target, b[0], b[1], color); } }
function coloredQuad(target: number[], a: readonly [number, number], b: readonly [number, number], c: readonly [number, number], d: readonly [number, number], ca: RuntimeColor, cb: RuntimeColor, cc: RuntimeColor, cd: RuntimeColor): void { vertex(target, a[0], a[1], ca); vertex(target, b[0], b[1], cb); vertex(target, c[0], c[1], cc); vertex(target, c[0], c[1], cc); vertex(target, b[0], b[1], cb); vertex(target, d[0], d[1], cd); }
function paintQuad(target: number[], rect: LayoutRect, paint: RuntimePaintSource, opacity: number, clip: LayoutRect | undefined, transform: { rotation: number; scaleX: number; scaleY: number }, glyphRect: LayoutRect): void { const clipped = transform.rotation === 0 ? intersect(rect, clip) : rect; if (!clipped) return; const divisions = paint.kind === 'solid' ? 1 : 8; for (let row = 0; row < divisions; row++) for (let column = 0; column < divisions; column++) { const x0 = clipped.x + clipped.width * column / divisions, x1 = clipped.x + clipped.width * (column + 1) / divisions, y0 = clipped.y + clipped.height * row / divisions, y1 = clipped.y + clipped.height * (row + 1) / divisions, a = transformPoint(x0, y0, transform, glyphRect), b = transformPoint(x1, y0, transform, glyphRect), c = transformPoint(x0, y1, transform, glyphRect), d = transformPoint(x1, y1, transform, glyphRect); coloredQuad(target, a, b, c, d, samplePaint(paint, x0, y0, glyphRect, opacity), samplePaint(paint, x1, y0, glyphRect, opacity), samplePaint(paint, x0, y1, glyphRect, opacity), samplePaint(paint, x1, y1, glyphRect, opacity)); } }
function transformPoint(x: number, y: number, transform: { rotation: number; scaleX: number; scaleY: number }, rect: LayoutRect): readonly [number, number] { const cx = rect.x + rect.width * 0.5, cy = rect.y + rect.height * 0.5, dx = (x - cx) * transform.scaleX, dy = (y - cy) * transform.scaleY, cosine = Math.cos(transform.rotation), sine = Math.sin(transform.rotation); return [cx + dx * cosine - dy * sine, cy + dx * sine + dy * cosine]; }
function samplePaint(paint: RuntimePaintSource, x: number, y: number, rect: LayoutRect, opacity: number): RuntimeColor { if (paint.kind === 'solid') return alpha(paint.color, opacity); const u = rect.width > 0 ? (x - rect.x) / rect.width : 0, v = rect.height > 0 ? (y - rect.y) / rect.height : 0; let amount: number; if (paint.kind === 'linear-gradient') { const dx = paint.end[0] - paint.start[0], dy = paint.end[1] - paint.start[1], denominator = dx * dx + dy * dy; amount = denominator > 0 ? ((u - paint.start[0]) * dx + (v - paint.start[1]) * dy) / denominator : 0; } else amount = paint.radius > 0 ? Math.hypot(u - paint.center[0], v - paint.center[1]) / paint.radius : 0; return alpha(interpolateStops(paint.stops, clamp(amount, 0, 1)), opacity); }
function interpolateStops(stops: readonly { readonly offset: number; readonly color: RuntimeColor }[], amount: number): RuntimeColor { const first = stops[0]!, last = stops[stops.length - 1]!; if (amount <= first.offset) return first.color; if (amount >= last.offset) return last.color; const rightIndex = stops.findIndex(stop => stop.offset >= amount), right = stops[rightIndex]!, left = stops[rightIndex - 1]!, span = right.offset - left.offset, mix = span > 0 ? (amount - left.offset) / span : 0; return [lerp(left.color[0], right.color[0], mix), lerp(left.color[1], right.color[1], mix), lerp(left.color[2], right.color[2], mix), lerp(left.color[3], right.color[3], mix)]; }
function intersect(rect: LayoutRect, clip: LayoutRect | undefined): LayoutRect | undefined { if (!clip) return rect; const x = Math.max(rect.x, clip.x), y = Math.max(rect.y, clip.y), right = Math.min(rect.x + rect.width, clip.x + clip.width), bottom = Math.min(rect.y + rect.height, clip.y + clip.height); return right > x && bottom > y ? { x, y, width: right - x, height: bottom - y } : undefined; }
function alpha(color: readonly [number, number, number, number], opacity: number): RuntimeColor { return [color[0], color[1], color[2], color[3] * clamp(opacity, 0, 1)]; }
function lerp(a: number, b: number, amount: number): number { return a + (b - a) * amount; }
function clamp(value: number, minimum: number, maximum: number): number { return Math.max(minimum, Math.min(maximum, value)); }
function ensureBudget(values: readonly number[], maximumBytes: number): void { if (values.length * Float32Array.BYTES_PER_ELEMENT > maximumBytes) throw new Error('E_LAYOUT_GPU_BUDGET'); }
function vertex(target: number[], x: number, y: number, color: readonly number[]): void { target.push(x, y, color[0]!, color[1]!, color[2]!, color[3]!); }
function hashColor(value: string): readonly [number, number, number, number] { let hash = 2166136261; for (let index = 0; index < value.length; index++) hash = Math.imul(hash ^ value.charCodeAt(index), 16777619); return [((hash >>> 0) & 255) / 255, ((hash >>> 8) & 255) / 255, ((hash >>> 16) & 255) / 255, 1]; }
function align4(value: number): number { return (value + 3) & ~3; }

export const LAYOUT_GPU_WGSL = /* wgsl */`
struct VertexOut { @builtin(position) position: vec4f, @location(0) color: vec4f }
@vertex fn vs(@location(0) position: vec2f, @location(1) color: vec4f) -> VertexOut {
  var out: VertexOut; out.position = vec4f(position, 0, 1); out.color = color; return out;
}
@fragment fn fs(input: VertexOut) -> @location(0) vec4f { return input.color; }
`;
