import type { RuntimeTextDocument, TextBlockPose, TextEvaluateUpdates } from '../../text/parameterized/runtime-types.js';

export type RuntimeLength = { readonly unit: 'point' | 'percent' | 'fraction'; readonly value: number } | { readonly unit: 'hug' | 'fill' };
export type RuntimeEdge = readonly [RuntimeLength, RuntimeLength, RuntimeLength, RuntimeLength];
export interface RuntimeStyle { readonly display?: 'flex' | 'grid' | 'none'; readonly position?: 'relative' | 'absolute'; readonly direction?: 'row' | 'column'; readonly writingDirection?: 'ltr' | 'rtl'; readonly wrap?: boolean; readonly width?: RuntimeLength; readonly height?: RuntimeLength; readonly minWidth?: RuntimeLength; readonly maxWidth?: RuntimeLength; readonly minHeight?: RuntimeLength; readonly maxHeight?: RuntimeLength; readonly aspectRatio?: number; readonly margin?: RuntimeEdge; readonly padding?: RuntimeEdge; readonly inset?: RuntimeEdge; readonly gap?: readonly [RuntimeLength, RuntimeLength]; readonly justify?: 'start' | 'center' | 'end' | 'space-between' | 'space-around' | 'space-evenly'; readonly align?: 'start' | 'center' | 'end' | 'stretch'; readonly justifySelf?: 'auto' | 'start' | 'center' | 'end' | 'stretch'; readonly overflow?: 'visible' | 'hidden' | 'scroll'; readonly gridColumns?: readonly { readonly min: RuntimeLength; readonly max?: RuntimeLength }[]; readonly gridRows?: readonly { readonly min: RuntimeLength; readonly max?: RuntimeLength }[]; readonly gridPlacement?: { readonly column: number; readonly row: number; readonly columnSpan?: number; readonly rowSpan?: number }; readonly reflow?: { readonly duration: number; readonly easing: readonly [number, number, number, number] }; }
export interface RuntimeVisual { readonly opacity?: number; readonly background?: readonly [number, number, number, number]; readonly borderColor?: readonly [number, number, number, number]; readonly borderWidth?: readonly [number, number, number, number]; readonly cornerRadius?: readonly [number, number, number, number]; readonly clip?: boolean; }
export interface RuntimeComponent { readonly artboard: string; readonly fit?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down'; readonly alignment?: readonly [number, number]; readonly sizing?: 'node' | 'leaf' | 'layout'; readonly playback?: { readonly mode: 'simple' | 'remap' | 'mix'; readonly speed?: number; readonly paused?: boolean; readonly quantize?: number; readonly stateful?: boolean; readonly remapPort?: string; readonly mixPort?: string }; readonly exposedInputs?: readonly string[]; readonly exposedEvents?: readonly string[]; }
export interface RuntimeList { readonly dataPort: string; readonly templateArtboard: string; readonly direction: 'row' | 'column'; readonly itemExtent: number; readonly gap?: number; readonly virtualize?: boolean; readonly buffer?: number; readonly carousel?: boolean; }
export interface RuntimeNSlice { readonly source: { readonly kind: 'asset'; readonly asset: string } | { readonly kind: 'node'; readonly node: string }; readonly sourceSize: readonly [number, number]; readonly xCuts: readonly number[]; readonly yCuts: readonly number[]; readonly tileModes?: readonly ('stretch' | 'repeat' | 'mirror')[]; }
export interface RuntimeScroll { readonly axis: 'x' | 'y' | 'both'; readonly mode?: 'clamped' | 'elastic' | 'infinite'; readonly snap?: number; readonly friction?: number; readonly elasticity?: number; readonly scrollbar?: { readonly node: string; readonly autoSize?: boolean }; }
export interface RuntimeNode { readonly id: string; readonly parent?: string; readonly kind: 'container' | 'leaf' | 'text' | 'image' | 'component' | 'list' | 'n-slice'; readonly style: RuntimeStyle; readonly visual?: RuntimeVisual; readonly intrinsicSize?: readonly [number, number]; readonly text?: string; readonly asset?: string; readonly component?: RuntimeComponent; readonly list?: RuntimeList; readonly nSlice?: RuntimeNSlice; readonly scroll?: RuntimeScroll; }
export interface RuntimeArtboard { readonly id: string; readonly width: number; readonly height: number; readonly root: string; readonly nodes: readonly RuntimeNode[]; }
export interface RuntimeRootInstance { readonly id: string; readonly artboard: string; readonly fit?: RuntimeComponent['fit']; readonly alignment?: readonly [number, number]; readonly transform?: readonly [number, number, number, number, number, number]; }
export interface RuntimeLayoutDocument extends RuntimeTextDocument { readonly format: 'haiyue-responsive-layout-2d'; readonly version: 1; readonly extension: 'org.haiyue.layout-2d@1'; readonly assets: readonly RuntimeAsset[]; readonly artboards: readonly RuntimeArtboard[]; readonly instances: readonly RuntimeRootInstance[]; }
export type RuntimeAsset = { readonly id: string; readonly kind: 'folder'; readonly children: readonly string[] } | { readonly id: string; readonly kind: 'image'; readonly width: number; readonly height: number; readonly source: RuntimeAssetSource } | { readonly id: string; readonly kind: 'font'; readonly family: string; readonly weight: number; readonly style: 'normal' | 'italic'; readonly metrics: import('../../text/parameterized/runtime-types.js').RuntimeFontMetrics; readonly source: RuntimeAssetSource } | { readonly id: string; readonly kind: 'audio'; readonly duration: number; readonly sampleRate: number; readonly channels: number; readonly source: RuntimeAssetSource } | { readonly id: string; readonly kind: 'blob' | 'manifest' | 'text'; readonly source: RuntimeAssetSource; readonly [key: string]: unknown };
export type RuntimeAssetSource = { readonly kind: 'embedded'; readonly data: ArrayLike<number>; readonly integrity: string } | { readonly kind: 'referenced'; readonly uri: string; readonly integrity: string } | { readonly kind: 'hosted'; readonly slot: string; readonly fallbackAsset?: string; readonly integrity?: string };

export interface LayoutRect { readonly x: number; readonly y: number; readonly width: number; readonly height: number; }
export interface NSlicePatch { readonly x: number; readonly y: number; readonly width: number; readonly height: number; readonly source: readonly [number, number, number, number]; readonly tileMode: 'stretch' | 'repeat' | 'mirror'; }
export interface LayoutNodePose { readonly key: string; readonly instanceId: string; readonly artboardId: string; readonly nodeId: string; readonly kind: RuntimeNode['kind']; readonly rect: LayoutRect; readonly clip?: LayoutRect; readonly opacity: number; readonly background?: readonly [number, number, number, number]; readonly borderColor?: readonly [number, number, number, number]; readonly borderWidth: readonly [number, number, number, number]; readonly cornerRadius: readonly [number, number, number, number]; readonly asset?: string; readonly text?: TextBlockPose; readonly nSlice?: readonly NSlicePatch[]; readonly item?: unknown; }
export interface LayoutInstancePose { readonly id: string; readonly artboardId: string; readonly parentId?: string; readonly hostNode?: string; readonly rect: LayoutRect; readonly times: readonly number[]; readonly mixWeight: number; readonly inputs: Readonly<Record<string, unknown>>; readonly events: readonly { readonly name: string; readonly payload?: unknown }[]; }
export interface LayoutEvaluation { readonly viewport: readonly [number, number]; readonly dpr: number; readonly time: number; readonly nodes: readonly LayoutNodePose[]; readonly instances: readonly LayoutInstancePose[]; readonly visibleListItems: number; readonly layoutPasses: number; }
export interface LayoutScrollInput { readonly offset?: readonly [number, number]; readonly velocity?: readonly [number, number]; readonly active?: boolean; readonly settled?: boolean; }
export interface LayoutEvaluateRequest extends TextEvaluateUpdates { readonly viewport: readonly [number, number]; readonly dpr: number; readonly time: number; readonly scroll?: Readonly<Record<string, LayoutScrollInput>>; readonly lists?: Readonly<Record<string, readonly unknown[]>>; readonly componentReplacements?: Readonly<Record<string, string>>; readonly componentInputs?: Readonly<Record<string, Readonly<Record<string, unknown>>>>; readonly componentEvents?: Readonly<Record<string, readonly { readonly name: string; readonly payload?: unknown }[]>>; readonly componentStateTimes?: Readonly<Record<string, number>>; readonly priorRects?: Readonly<Record<string, LayoutRect>>; readonly reflowProgress?: number; readonly signal?: AbortSignal; }
export interface LayoutRuntimeLimits { readonly maxGlyphs: number; readonly maxLines: number; readonly maxLayoutPasses: number; readonly maxNestedDepth: number; readonly maxComponentInstances: number; readonly maxListItems: number; readonly maxVirtualizedWindow: number; readonly maxNslicePatches: number; }
