import { semanticsFail } from './diagnostics.js';
import { HYA_SEMANTICS_EXTENSION_ID, HYA_SEMANTICS_FORMAT, HYA_SEMANTICS_VERSION, type HyaSemanticsDocument, type SemanticsParseOptions } from './types.js';

type Row = Record<string, unknown>;
export function parseHyaSemantics(value: unknown, options: SemanticsParseOptions = {}): HyaSemanticsDocument {
  const maxNodes = positiveLimit(options.maxNodes ?? 250_000, '$.limits.maxNodes'), maxDepth = positiveLimit(options.maxDepth ?? 128, '$.limits.maxDepth'), maxStringBytes = positiveLimit(options.maxStringBytes ?? 4 * 1024 * 1024, '$.limits.maxStringBytes');
  const root = object(value, '$'); keys(root, ['format', 'version', 'extension', 'nodes', 'reducedMotion'], '$'); literal(root.format, HYA_SEMANTICS_FORMAT, '$.format'); literal(root.version, HYA_SEMANTICS_VERSION, '$.version'); literal(root.extension, HYA_SEMANTICS_EXTENSION_ID, '$.extension'); const nodes = array(root.nodes, '$.nodes'); if (nodes.length > maxNodes) semanticsFail('E_SEMANTICS_LIMIT', '$.nodes', 'node count exceeds budget'); const ids = new Set<string>(); nodes.forEach((candidate, index) => { const id = identifier(object(candidate, `$.nodes[${index}]`).id, `$.nodes[${index}].id`, maxStringBytes); if (ids.has(id)) semanticsFail('E_SEMANTICS_FORMAT', `$.nodes[${index}].id`, 'duplicate id'); ids.add(id); });
  nodes.forEach((candidate, index) => { const path = `$.nodes[${index}]`, node = object(candidate, path); keys(node, ['id', 'target', 'parent', 'role', 'label', 'value', 'hint', 'headingLevel', 'traits', 'state', 'capabilities', 'actions', 'live', 'readingOrder', 'navigationOrder'], path); identifier(node.id, `${path}.id`, maxStringBytes); identifier(node.target, `${path}.target`, maxStringBytes); if (node.parent !== undefined) reference(node.parent, ids, `${path}.parent`); const role = enumeration(node.role, ['none', 'group', 'text', 'button', 'link', 'image', 'heading', 'checkbox', 'radio', 'switch', 'slider', 'progress', 'textbox', 'list', 'list-item', 'menu', 'menu-item', 'dialog'], `${path}.role`); if (node.label !== undefined) semanticValue(node.label, `${path}.label`, ['string'], maxStringBytes); if (node.value !== undefined) semanticValue(node.value, `${path}.value`, ['string', 'number'], maxStringBytes); if (node.hint !== undefined) semanticValue(node.hint, `${path}.hint`, ['string'], maxStringBytes); if (node.headingLevel !== undefined) { const level = integer(node.headingLevel, `${path}.headingLevel`); if (level < 1 || level > 6 || role !== 'heading') semanticsFail('E_SEMANTICS_NUMBER', `${path}.headingLevel`, 'heading level 1..6 requires heading role'); } if (node.traits !== undefined) uniqueEnums(node.traits, ['button', 'link', 'image', 'header', 'adjustable', 'selected', 'disabled'], `${path}.traits`); if (node.actions !== undefined) uniqueEnums(node.actions, ['tap', 'increase', 'decrease', 'focus'], `${path}.actions`); if (node.live !== undefined) enumeration(node.live, ['off', 'polite', 'assertive'], `${path}.live`); finite(node.readingOrder, `${path}.readingOrder`); finite(node.navigationOrder, `${path}.navigationOrder`); if (node.state !== undefined) { const state = object(node.state, `${path}.state`); keys(state, ['hidden', 'disabled', 'focused', 'expanded', 'selected', 'checked', 'mixed', 'toggled', 'required', 'readOnly', 'modal', 'obscured', 'multiline'], `${path}.state`); for (const [key, stateValue] of Object.entries(state)) semanticValue(stateValue, `${path}.state.${key}`, ['boolean'], maxStringBytes); } if (node.capabilities !== undefined) { const capabilities = object(node.capabilities, `${path}.capabilities`); keys(capabilities, ['expandable', 'selectable', 'checkable', 'toggleable', 'requirable', 'enablable', 'focusable'], `${path}.capabilities`); for (const [key, capability] of Object.entries(capabilities)) if (typeof capability !== 'boolean') semanticsFail('E_SEMANTICS_FORMAT', `${path}.capabilities.${key}`, 'expected boolean'); } });
  validateGraph(nodes, maxDepth); const reduced = object(root.reducedMotion, '$.reducedMotion'), mode = enumeration(reduced.mode, ['ignore', 'respect'], '$.reducedMotion.mode'); if (mode === 'ignore') keys(reduced, ['mode'], '$.reducedMotion'); else { keys(reduced, ['mode', 'decorative', 'essential', 'durationScale', 'disableParallax'], '$.reducedMotion'); enumeration(reduced.decorative, ['pause', 'stop', 'continue'], '$.reducedMotion.decorative'); enumeration(reduced.essential, ['retain', 'reduce'], '$.reducedMotion.essential'); const scale = finite(reduced.durationScale, '$.reducedMotion.durationScale'); if (scale < 0 || scale > 1) semanticsFail('E_SEMANTICS_NUMBER', '$.reducedMotion.durationScale', 'duration scale must be within 0..1'); if (typeof reduced.disableParallax !== 'boolean') semanticsFail('E_SEMANTICS_FORMAT', '$.reducedMotion.disableParallax', 'expected boolean'); }
  return deepFreeze(structuredClone(root) as unknown as HyaSemanticsDocument);
}

function semanticValue(value: unknown, path: string, types: readonly string[], maxBytes: number): void { const row = object(value, path), kind = enumeration(row.kind, ['literal', 'binding'], `${path}.kind`); keys(row, kind === 'literal' ? ['kind', 'value'] : ['kind', 'binding'], path); if (kind === 'binding') identifier(row.binding, `${path}.binding`, maxBytes); else if (!types.includes(typeof row.value)) semanticsFail('E_SEMANTICS_FORMAT', `${path}.value`, `expected ${types.join(' or ')}`); else if (typeof row.value === 'number') finite(row.value, `${path}.value`); else if (typeof row.value === 'string') identifier(row.value, `${path}.value`, maxBytes, true); }
function validateGraph(nodes: unknown[], maxDepth: number): void { const parents = new Map<string, string | undefined>(); nodes.forEach((entry, index) => { const row = object(entry, `$.nodes[${index}]`); parents.set(row.id as string, row.parent as string | undefined); }); for (const id of parents.keys()) { const seen = new Set<string>(); let current: string | undefined = id, depth = 0; while (current !== undefined) { if (seen.has(current)) semanticsFail('E_SEMANTICS_GRAPH', '$.nodes', `semantic cycle through ${current}`); if (++depth > maxDepth) semanticsFail('E_SEMANTICS_LIMIT', '$.nodes', 'semantic depth exceeds budget'); seen.add(current); current = parents.get(current); } } }
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); } return value; }
function object(value: unknown, path: string): Row { if (!value || typeof value !== 'object' || Array.isArray(value)) semanticsFail('E_SEMANTICS_FORMAT', path, 'expected object'); return value as Row; }
function array(value: unknown, path: string): unknown[] { if (!Array.isArray(value)) semanticsFail('E_SEMANTICS_FORMAT', path, 'expected array'); return value; }
function keys(value: Row, allowed: readonly string[], path: string): void { const set = new Set(allowed); for (const key of Object.keys(value)) if (!set.has(key)) semanticsFail('E_SEMANTICS_FORMAT', `${path}.${key}`, 'unknown field'); }
function literal(value: unknown, expected: unknown, path: string): void { if (value !== expected) semanticsFail('E_SEMANTICS_FORMAT', path, `expected ${String(expected)}`); }
function enumeration<T extends string>(value: unknown, allowed: readonly T[], path: string): T { if (typeof value !== 'string' || !allowed.includes(value as T)) semanticsFail('E_SEMANTICS_FORMAT', path, `expected one of ${allowed.join(', ')}`); return value as T; }
function identifier(value: unknown, path: string, maxBytes: number, allowEmpty = false): string { if (typeof value !== 'string' || (!allowEmpty && value.length === 0)) semanticsFail('E_SEMANTICS_FORMAT', path, 'expected string'); if (new TextEncoder().encode(value).length > maxBytes) semanticsFail('E_SEMANTICS_LIMIT', path, 'string exceeds byte budget'); return value; }
function reference(value: unknown, ids: Set<string>, path: string): string { const id = identifier(value, path, 4 * 1024 * 1024); if (!ids.has(id)) semanticsFail('E_SEMANTICS_REFERENCE', path, `unknown reference ${id}`); return id; }
function finite(value: unknown, path: string): number { if (typeof value !== 'number' || !Number.isFinite(value)) semanticsFail('E_SEMANTICS_NUMBER', path, 'expected finite number'); return value; }
function integer(value: unknown, path: string): number { const result = finite(value, path); if (!Number.isSafeInteger(result)) semanticsFail('E_SEMANTICS_NUMBER', path, 'expected safe integer'); return result; }
function positiveLimit(value: number, path: string): number { if (!Number.isSafeInteger(value) || value < 1) semanticsFail('E_SEMANTICS_LIMIT', path, 'expected positive safe integer'); return value; }
function uniqueEnums<T extends string>(value: unknown, allowed: readonly T[], path: string): void { const seen = new Set<T>(); array(value, path).forEach((entry, index) => { const result = enumeration(entry, allowed, `${path}[${index}]`); if (seen.has(result)) semanticsFail('E_SEMANTICS_FORMAT', `${path}[${index}]`, 'duplicate entry'); seen.add(result); }); }
