// Generated by scripts/webgpu-gate/verify-progressive-path-tracing-shaders.mjs. Do not edit.
export const RAY_DENOISE_SHADER_ARTIFACT = {
  "format": "haiyue-precompiled-shader-artifact",
  "version": 2,
  "compilerVersion": "shader-language-ray-progressive-v1",
  "source": {
    "kind": "module-family",
    "path": "extensions/src/ray-tracing/denoise/shaders/denoise-family.json",
    "sha256": "a3761d72e23edd21b33d8b59bc31975cf4636baf7b3ef8b99ebf3839fff5f563"
  },
  "canonicalHash": "47f815f431bd4c42c1b0fe63a6de380b07835e7f070c0155957d745beb6f8c80",
  "typedModuleHash": "f8e99ab39fbc1e4a35dd0bf69d7bd5390bae60bb61659a2375ca896a66427e79",
  "passes": {
    "ray-denoise-temporal": {
      "id": "ray-denoise-temporal",
      "code": "struct DenoiseParams {\n  image: vec4u,\n  controls: vec4f,\n  reserved0: vec4f,\n  reserved1: vec4f,\n}\n@group(0) @binding(0) var<uniform> params: DenoiseParams;\n@group(0) @binding(1) var accumulation: texture_2d<f32>;\n@group(0) @binding(2) var moments: texture_2d<f32>;\n@group(0) @binding(3) var feature: texture_2d<f32>;\n@group(0) @binding(4) var previousDenoised: texture_2d<f32>;\n@group(0) @binding(5) var temporalOutput: texture_storage_2d<rgba16float, write>;\n\nfn luma(value: vec3f) -> f32 { return dot(value, vec3f(0.2126, 0.7152, 0.0722)); }\n@compute @workgroup_size(8, 8, 1)\nfn temporal_main(@builtin(global_invocation_id) globalId: vec3u) {\n  if (globalId.x >= params.image.x || globalId.y >= params.image.y) { return; }\n  let pixel = vec2i(globalId.xy); let limit = vec2i(params.image.xy) - vec2i(1);\n  let current = textureLoad(accumulation, pixel, 0).rgb; var lower = current; var upper = current;\n  for (var y = -1; y <= 1; y++) { for (var x = -1; x <= 1; x++) {\n    let neighbor = textureLoad(accumulation, clamp(pixel + vec2i(x, y), vec2i(0), limit), 0).rgb;\n    lower = min(lower, neighbor); upper = max(upper, neighbor);\n  }}\n  let previous = clamp(textureLoad(previousDenoised, pixel, 0).rgb, lower, upper);\n  let moment = textureLoad(moments, pixel, 0).rg; let variance = max(0.0, moment.y - moment.x * moment.x);\n  let featureValue = textureLoad(feature, pixel, 0); let difference = abs(luma(previous) - featureValue.x);\n  let threshold = params.controls.y + sqrt(variance) * params.controls.w;\n  var weight = params.controls.x * exp(-difference / max(threshold, 1e-5));\n  if (params.image.z == 0u || params.image.w != 0u || difference > threshold * 4.0) { weight = 0.0; }\n  textureStore(temporalOutput, pixel, vec4f(mix(current, previous, clamp(weight, 0.0, 0.95)), 1.0));\n}\n",
      "entryPoints": {
        "compute": "temporal_main"
      },
      "bindGroups": [
        {
          "logicalSpace": "pass",
          "logicalGroup": 3,
          "physicalGroup": 0,
          "owner": "artifact",
          "bindings": [
            {
              "id": "denoise.params",
              "binding": 0,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "buffer",
                "bufferType": "uniform",
                "hasDynamicOffset": false,
                "minBindingSize": 64
              }
            },
            {
              "id": "denoise.accumulation",
              "binding": 1,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.moments",
              "binding": 2,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.feature",
              "binding": 3,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.previous",
              "binding": 4,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.temporalOutput",
              "binding": 5,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "storage-texture",
                "access": "write-only",
                "format": "rgba16float",
                "viewDimension": "2d"
              }
            }
          ]
        }
      ],
      "uniformBlocks": [
        {
          "id": "denoise.params",
          "alignment": 16,
          "byteSize": 64,
          "fields": [
            {
              "name": "raw",
              "type": "array<u32,16>",
              "offset": 0,
              "size": 64,
              "arrayStride": 4
            }
          ]
        }
      ],
      "vertexBuffers": [],
      "varyings": [],
      "renderTargets": [],
      "capabilities": [
        "compute",
        "sampled-texture",
        "storage-texture"
      ],
      "passRequirements": [
        "webgpu",
        "maxStorageTexturesPerShaderStage>=4",
        "maxBindingsPerBindGroup>=9"
      ],
      "sourceMap": [
        {
          "sourceId": "ray-denoise-temporal",
          "sourceName": "extensions/src/ray-tracing/denoise/shaders/temporal-denoise.wgsl",
          "generatedStartLine": 1,
          "generatedEndLine": 32,
          "sourceStartLine": 1,
          "sourceStartColumn": 1
        }
      ],
      "canonicalHash": "d14280ce3dbed22a816580b6c8dce6f57cf7f1ead2be9b6d4e64d7f9f378d019"
    },
    "ray-denoise-spatial": {
      "id": "ray-denoise-spatial",
      "code": "struct DenoiseParams {\n  image: vec4u,\n  controls: vec4f,\n  reserved0: vec4f,\n  reserved1: vec4f,\n}\n@group(0) @binding(0) var<uniform> params: DenoiseParams;\n@group(0) @binding(1) var temporalInput: texture_2d<f32>;\n@group(0) @binding(2) var moments: texture_2d<f32>;\n@group(0) @binding(3) var feature: texture_2d<f32>;\n@group(0) @binding(4) var spatialOutput: texture_storage_2d<rgba16float, write>;\n\nfn luma(value: vec3f) -> f32 { return dot(value, vec3f(0.2126, 0.7152, 0.0722)); }\n@compute @workgroup_size(8, 8, 1)\nfn spatial_main(@builtin(global_invocation_id) globalId: vec3u) {\n  if (globalId.x >= params.image.x || globalId.y >= params.image.y) { return; }\n  let pixel = vec2i(globalId.xy); let limit = vec2i(params.image.xy) - vec2i(1);\n  let center = textureLoad(temporalInput, pixel, 0).rgb; let centerFeature = textureLoad(feature, pixel, 0);\n  let moment = textureLoad(moments, pixel, 0).rg; let variance = max(0.0, moment.y - moment.x * moment.x);\n  let colorScale = params.controls.y + sqrt(variance) * params.controls.w;\n  var total = center * 4.0; var totalWeight = 4.0;\n  for (var y = -1; y <= 1; y++) { for (var x = -1; x <= 1; x++) {\n    if (x == 0 && y == 0) { continue; }\n    let location = clamp(pixel + vec2i(x, y), vec2i(0), limit);\n    let value = textureLoad(temporalInput, location, 0).rgb; let featureValue = textureLoad(feature, location, 0);\n    let colorDifference = abs(luma(value) - luma(center));\n    let featureDifference = abs(featureValue.x - centerFeature.x) + abs(featureValue.y - centerFeature.y);\n    let distanceWeight = select(0.7, 1.0, x == 0 || y == 0);\n    let weight = distanceWeight * exp(-colorDifference / max(colorScale, 1e-5)) * exp(-featureDifference / max(params.controls.z, 1e-5));\n    total += value * weight; totalWeight += weight;\n  }}\n  textureStore(spatialOutput, pixel, vec4f(total / totalWeight, 1.0));\n}\n",
      "entryPoints": {
        "compute": "spatial_main"
      },
      "bindGroups": [
        {
          "logicalSpace": "pass",
          "logicalGroup": 3,
          "physicalGroup": 0,
          "owner": "artifact",
          "bindings": [
            {
              "id": "denoise.params",
              "binding": 0,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "buffer",
                "bufferType": "uniform",
                "hasDynamicOffset": false,
                "minBindingSize": 64
              }
            },
            {
              "id": "denoise.temporalInput",
              "binding": 1,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.moments",
              "binding": 2,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.feature",
              "binding": 3,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "texture",
                "sampleType": "unfilterable-float",
                "viewDimension": "2d",
                "multisampled": false
              }
            },
            {
              "id": "denoise.spatialOutput",
              "binding": 4,
              "visibility": [
                "compute"
              ],
              "layout": {
                "kind": "storage-texture",
                "access": "write-only",
                "format": "rgba16float",
                "viewDimension": "2d"
              }
            }
          ]
        }
      ],
      "uniformBlocks": [
        {
          "id": "denoise.params",
          "alignment": 16,
          "byteSize": 64,
          "fields": [
            {
              "name": "raw",
              "type": "array<u32,16>",
              "offset": 0,
              "size": 64,
              "arrayStride": 4
            }
          ]
        }
      ],
      "vertexBuffers": [],
      "varyings": [],
      "renderTargets": [],
      "capabilities": [
        "compute",
        "sampled-texture",
        "storage-texture"
      ],
      "passRequirements": [
        "webgpu",
        "maxStorageTexturesPerShaderStage>=4",
        "maxBindingsPerBindGroup>=9"
      ],
      "sourceMap": [
        {
          "sourceId": "ray-denoise-spatial",
          "sourceName": "extensions/src/ray-tracing/denoise/shaders/spatial-denoise.wgsl",
          "generatedStartLine": 1,
          "generatedEndLine": 34,
          "sourceStartLine": 1,
          "sourceStartColumn": 1
        }
      ],
      "canonicalHash": "41165dc5450238782d37b2868dcae52854a654e359acfcf3f638edff14fe3cf1"
    }
  },
  "artifactHash": "b2e55dafdf2be903e797241d14a98e76bee2c64e95dd889069a27044afe4d1aa"
} as const;
